### PR TITLE
Fix random download of source tarball instead of binary

### LINKED ISSUE #44: [Bug]: Invalid downloaded binary package
Some of the candidate binary packages are identified as invalid during installation

image

It's mostly the same set of packages / versions.

Behaviour is inconsistent, re-running the workflow seems to resolve the problem sometimes

https://github.com/insightsengineering/teal.reporter/actions/runs/9201604335/job/25310820679
https://github.com/insightsengineering/teal.modules.clinical/actions/runs/9199325232/job/25310824740
https://github.com/insightsengineering/tern.mmrm/actions/runs/9199326071/job/25310826318
https://github.com/insightsengineering/tern.rbmi/actions/runs/9199327395/job/25310829889
https://github.com/insightsengineering/teal.osprey/actions/runs/9199329133/job/25310833797
https://github.com/insightsengineering/citril/actions/runs/9201882022/job/25310788844
https://github.com/insightsengineering/rtables/actions/runs/9201677563/job/25310818536

### PR DESCRIPTION
**Pull request by averissimo**
# Pull Request

- Closes #44 

Part of https://github.com/insightsengineering/coredev-tasks/issues/546

Upstream bug: https://github.com/r-lib/pkgdepends/issues/367

#### Changes description:

- Removes sources links that include "src/contrib/Archive"
  - When `{pkgdepends}` attempts to download the tarball, it will try all sources and archive-based sources are only source-code
- Re-downloads tarball using mirror.
  - Last attempt to explicitly use `ppm` snapshot mirror

#### Testing

1. Install or load this branch
    - `renv::install("insightsengineering/verdepcheck@fix-random-download%40main")`
3. Clone [`{tmc}`](https://github.com/insightsengineering/teal.modules.clinical)
    - checkout `546-fix-verdepcheck@main` branch
5. Run all strategies:
    - `verdepcheck::min_cohort_deps_check("/path/to/tmc")`
    - `verdepcheck::min_isolated_deps_check("/path/to/tmc")`
    - `verdepcheck::release_deps_check("/path/to/tmc")`
    - `verdepcheck::max_deps_check("/path/to/tmc")`

### CODE REVIEW

File: R/check.R [hunk 1]
```diff
@@ -105,9 +105,59 @@ execute_ip <- function(ip, path, build_args, check_args, ...) {
...
+        utils::untar(tarfile = tar_file, exdir = "./")
+        tryCatch(
+          {
+            asNamespace("pkgdepends")$verify_extracted_package(res$package[ix_el], "./")
+          },
+          error = function(error) {
+            cli::cli_warn("{res$package[ix_el]} binary is not valid, trying to re-download.")
+            # Attempts to download again using {pkgcache} / {pkgdepends} http methods
+            async_fun <- asNamespace("pkgcache")$async(function() {
+              asNamespace("pkgcache")$download_file(
```
Comment (averissimo) [inline R/check.R:148]: This does not have to be CRAN-friendly, although this is accepted as `{pkgdepends}` also uses `asNamespace`.

Preferred to use existing tools that underlying package instead of adding a new dependency.

Let's hope that the issue is solved upstream and these 2 chunks can be removed

**Comment by m7pr** [comment]
This is what I get

```r
> verdepcheck::min_cohort_deps_check(".")
✔ Loading metadata database ... done
ℹ Creating temporary DESCRIPTION file: C:\Users\kosinsm4\AppData\Local\Temp\RtmpUp5Hbc\file62bc20ee461a
ℹ Creating library directory: C:\Users\kosinsm4\AppData\Local\Temp\RtmpUp5Hbc\file62bc7c785e66
✔ Updated metadata database: 5.22 MB in 7 files.                                 
✔ Updating metadata database ... done                                      
Error : ! Could not solve package dependencies:                             
* deps::C:\Users\kosinsm4\AppData\Local\Temp\RtmpUp5Hbc\file62bc20ee461a:
  * Can't install dependency rtables=insightsengineering/rtables (>= 0.6.7.9003)
  * Can't install dependency rtables=insightsengineering/rtables
* rtables=insightsengineering/rtables: Can't install dependency formatters (>= 0.5.7.9000)
```

we are trying to pull rtables from github, but rtables also should get formatters from github : )

**Comment by m7pr** [comment]
I see the same for `min_isolated_deps_check`

```r
> verdepcheck::min_isolated_deps_check(".")
ℹ Creating temporary DESCRIPTION file: C:\Users\kosinsm4\AppData\Local\Temp\RtmpUp5Hbc\file62bc1f0d5dfc
ℹ Creating library directory: C:\Users\kosinsm4\AppData\Local\Temp\RtmpUp5Hbc\file62bc6a102857
Error : ! Could not solve package dependencies:                                  
* deps::C:\Users\kosinsm4\AppData\Local\Temp\RtmpUp5Hbc\file62bc1f0d5dfc: Can't install dependency rtables=insightsengineering/rtables (>= 0.6.7.9003)
* rtables=insightsengineering/rtables: Can't install dependency formatters (>= 0.5.7.9000)
```

It's caused by this rtables dependency on formatters. Should be resolved once `0.5.7` formatters is released to CRAN

**Comment by m7pr** [comment]
Last two give similar issues

```r
> verdepcheck::release_deps_check(".")
✔ Updated metadata database: 2.20 MB in 2 files.                          
✔ Updating metadata database ... done                                     
ℹ Creating temporary DESCRIPTION file: C:\Users\kosinsm4\AppData\Local\Temp\RtmpUp5Hbc\file62bc10a36729
ℹ Creating library directory: C:\Users\kosinsm4\AppData\Local\Temp\RtmpUp5Hbc\file62bc26fd7ec9
Error : ! Could not solve package dependencies:                            
* deps::C:\Users\kosinsm4\AppData\Local\Temp\RtmpUp5Hbc\file62bc10a36729: Can't install dependency rtables (>= 0.6.7.9003)
> verdepcheck::max_deps_check(".")
ℹ Creating temporary DESCRIPTION file: C:\Users\kosinsm4\AppData\Local\Temp\RtmpUp5Hbc\file62bc10285add
ℹ Creating library directory: C:\Users\kosinsm4\AppData\Local\Temp\RtmpUp5Hbc\file62bc64711b56
Error : ! Could not solve package dependencies:                              
* deps::C:\Users\kosinsm4\AppData\Local\Temp\RtmpUp5Hbc\file62bc10285add:
  * Can't install dependency rtables (>= 0.6.7.9003)
  * Can't install dependency insightsengineering/tern
  * Can't install dependency insightsengineering/rlistings
  * Can't install dependency insightsengineering/rtables
* insightsengineering/tern: Can't install dependency formatters (>= 0.5.7.9000)
* insightsengineering/rlistings: Can't install dependency formatters (>= 0.5.7.9000)
* insightsengineering/rtables: Can't install dependency formatters (>= 0.5.7.9000)
```

**Comment by averissimo** [comment]
My bad, please try using the `546-fix-verdepcheck@main` branch that:

- Doesn't have the most recent change
- It also has a fix for a package version

> we are trying to pull rtables from github, but rtables also should get formatters from github : )

This is a slippery slope as we would have to include secondary dependencies github repos in the DESCRIPTION file and that would grow very fast. (would we do that all the 188 primary and secondary+ dependency?)

We have to stop somewhere and for now we are only keeping primary. There's an argument though to include secondary `insightengineering` deps :thinking:

**Comment by averissimo** [comment]
You can also use any of the ones below:

- https://github.com/insightsengineering/teal.code
- https://github.com/insightsengineering/teal.logger
- https://github.com/insightsengineering/teal.widgets

**Comment by m7pr** [comment]
Retried with `546-fix-verdepcheck@main` branch for `teal.modules.clinical`

**Comment by m7pr** [comment]
Looks like I dont have LaTeX but everything else went fine for the first strategy that I tried
```r
verdepcheck::min_cohort_deps_check(".")
ℹ Creating temporary DESCRIPTION file: C:\Users\kosinsm4\AppData\Local\Temp\RtmpkZuXze\file5ebc52714aaf
ℹ Creating library directory: C:\Users\kosinsm4\AppData\Local\Temp\RtmpkZuXze\file5ebc49f57c33
✔ Updated metadata database: 5.23 MB in 8 files.                           
✔ Updating metadata database ... done                                      
ℹ Getting 180 pkgs (185.16 MB), 8 (25.09 MB) cached                         
✔ Got assertthat 0.2.1 (i386+x86_64-w64-mingw32) (56.02 kB)                                    
✔ Got base64enc 0.1-3 (i386+x86_64-w64-mingw32) (32.80 kB)                                     
✔ Got crul 1.4.2 (i386+x86_64-w64-mingw32) (676.83 kB)                                         
✔ Got abind 1.4-5 (i386+x86_64-w64-mingw32) (64.68 kB)                                         
✔ Got anytime 0.3.9 (i386+x86_64-w64-mingw32) (715.95 kB)                                      
✔ Got askpass 1.2.0 (i386+x86_64-w64-mingw32) (74.42 kB)                                       
✔ Got backports 1.4.1 (i386+x86_64-w64-mingw32) (105.18 kB)                                    
✔ Got brio 1.1.4 (i386+x86_64-w64-mingw32) (40.80 kB)                                          
✔ Got broom 1.0.5 (i386+x86_64-w64-mingw32) (1.94 MB)                                          
✔ Got commonmark 1.9.1 (i386+x86_64-w64-mingw32) (141.95 kB)                                   
✔ Got crayon 1.5.2 (i386+x86_64-w64-mingw32) (165.39 kB)                                       
✔ Got curl 5.2.1 (i386+x86_64-w64-mingw32) (3.22 MB)                                           
✔ Got data.table 1.15.4 (i386+x86_64-w64-mingw32) (2.41 MB)                                    
✔ Got fansi 1.0.6 (i386+x86_64-w64-mingw32) (320.43 kB)                                        
✔ Got fastmap 1.1.1 (i386+x86_64-w64-mingw32) (133.42 kB)                                      
✔ Got farver 2.1.1 (i386+x86_64-w64-mingw32) (1.51 MB)                                         
✔ Got flextable 0.9.5 (i386+x86_64-w64-mingw32) (1.38 MB)                                      
✔ Got glue 1.7.0 (i386+x86_64-w64-mingw32) (163.13 kB)                                         
✔ Got gridExtra 2.3 (i386+x86_64-w64-mingw32) (1.11 MB)                                        
✔ Got gtable 0.3.4 (i386+x86_64-w64-mingw32) (227.93 kB)                                       
✔ Got haven 2.5.4 (i386+x86_64-w64-mingw32) (755.93 kB)                                        
✔ Got magrittr 2.0.3 (i386+x86_64-w64-mingw32) (229.11 kB)                                     
✔ Got MatrixModels 0.5-3 (i386+x86_64-w64-mingw32) (422.45 kB)                                 
✔ Got memoise 2.0.1 (i386+x86_64-w64-mingw32) (51.62 kB)                                       
✔ Got mime 0.12 (i386+x86_64-w64-mingw32) (40.68 kB)                                           
✔ Got minqa 1.2.6 (i386+x86_64-w64-mingw32) (438.21 kB)                                        
✔ Got shinyWidgets 0.8.5 (i386+x86_64-w64-mingw32) (1.54 MB)                                   
✔ Got rbibutils 2.2.16 (i386+x86_64-w64-mingw32) (759.04 kB)                                   
✔ Got shinyvalidate 0.1.3 (i386+x86_64-w64-mingw32) (193.77 kB)                                
✔ Got sourcetools 0.1.7-1 (i386+x86_64-w64-mingw32) (126.84 kB)                                
✔ Got MESS 0.5.12 (i386+x86_64-w64-mingw32) (3.58 MB)                                          
✔ Got ragg 1.3.0 (i386+x86_64-w64-mingw32) (1.91 MB)                                           
✔ Got systemfonts 1.0.6 (i386+x86_64-w64-mingw32) (1.30 MB)                                    
✔ Got teal.code 0.5.0 (i386+x86_64-w64-mingw32) (204.73 kB)                                    
✔ Got teal 0.15.2 (i386+x86_64-w64-mingw32) (2.19 MB)                                          
✔ Got urltools 1.7.3 (i386+x86_64-w64-mingw32) (612.00 kB)                                     
✔ Got utf8 1.2.4 (i386+x86_64-w64-mingw32) (149.20 kB)                                         
✔ Got uuid 1.2-0 (i386+x86_64-w64-mingw32) (51.47 kB)                                          
✔ Got vctrs 0.6.5 (i386+x86_64-w64-mingw32) (1.34 MB)                                          
✔ Got viridisLite 0.4.2 (i386+x86_64-w64-mingw32) (1.30 MB)                                    
✔ Got crosstalk 1.2.1 (i386+x86_64-w64-mingw32) (416.80 kB)                                    
✔ Got diffobj 0.3.5 (i386+x86_64-w64-mingw32) (1.03 MB)                                        
✔ Got digest 0.6.35 (i386+x86_64-w64-mingw32) (217.29 kB)                                      
✔ Got cowplot 1.1.3 (i386+x86_64-w64-mingw32) (1.38 MB)                                        
✔ Got dplyr 1.1.4 (i386+x86_64-w64-mingw32) (1.59 MB)                                          
✔ Got DT 0.33 (i386+x86_64-w64-mingw32) (2.03 MB)                                              
✔ Got generics 0.1.3 (i386+x86_64-w64-mingw32) (83.89 kB)                                      
✔ Got gfonts 0.2.0 (i386+x86_64-w64-mingw32) (2.87 MB)                                         
✔ Got ggformula 0.12.0 (i386+x86_64-w64-mingw32) (1.83 MB)                                     
✔ Got nestcolor 0.1.2 (i386+x86_64-w64-mingw32) (441.81 kB)                                    
✔ Got nloptr 2.0.3 (i386+x86_64-w64-mingw32) (1.01 MB)                                         
✔ Got numDeriv 2016.8-1.1 (i386+x86_64-w64-mingw32) (117.50 kB)                                
✔ Got officer 0.6.5 (i386+x86_64-w64-mingw32) (1.73 MB)                                        
✔ Got R.methodsS3 1.8.2 (i386+x86_64-w64-mingw32) (85.30 kB)                                   
✔ Got RColorBrewer 1.1-3 (i386+x86_64-w64-mingw32) (54.57 kB)                                  
✔ Got quadprog 1.5-8 (i386+x86_64-w64-mingw32) (36.87 kB)                                      
✔ Got R.cache 0.16.0 (i386+x86_64-w64-mingw32) (114.60 kB)                                     
✔ Got stringr 1.5.1 (i386+x86_64-w64-mingw32) (324.14 kB)                                      
✔ Got quantreg 5.97 (i386+x86_64-w64-mingw32) (1.57 MB)                                        
✔ Got vroom 1.6.5 (i386+x86_64-w64-mingw32) (1.26 MB)                                          
✔ Got waldo 0.5.2 (i386+x86_64-w64-mingw32) (106.31 kB)                                        
✔ Got shinytest2 0.3.1 (i386+x86_64-w64-mingw32) (3.16 MB)                                     
✔ Got websocket 1.4.1 (i386+x86_64-w64-mingw32) (2.80 MB)                                      
✔ Got ellipsis 0.3.2 (i386+x86_64-w64-mingw32) (40.88 kB)                                      
✔ Got estimability 1.5 (i386+x86_64-w64-mingw32) (54.12 kB)                                    
✔ Got emmeans 1.10.1 (i386+x86_64-w64-mingw32) (2.22 MB)                                       
✔ Got htmltools 0.5.8.1 (i386+x86_64-w64-mingw32) (364.88 kB)                                  
✔ Got htmlwidgets 1.6.4 (i386+x86_64-w64-mingw32) (814.05 kB)                                  
✔ Got httpcode 0.3.0 (i386+x86_64-w64-mingw32) (35.56 kB)                                      
✔ Got httpuv 1.6.15 (i386+x86_64-w64-mingw32) (977.03 kB)                                      
✔ Got mosaicCore 0.9.4.0 (i386+x86_64-w64-mingw32) (200.94 kB)                                 
✔ Got munsell 0.5.1 (i386+x86_64-w64-mingw32) (246.01 kB)                                      
✔ Got mvtnorm 1.2-4 (i386+x86_64-w64-mingw32) (755.23 kB)                                      
✔ Got pbkrtest 0.5.2 (i386+x86_64-w64-mingw32) (194.83 kB)                                     
✔ Got mmrm 0.3.11 (i386+x86_64-w64-mingw32) (2.61 MB)                                          
✔ Got rematch2 2.1.2 (i386+x86_64-w64-mingw32) (49.10 kB)                                      
✔ Got rlang 1.1.3 (i386+x86_64-w64-mingw32) (1.61 MB)                                          
✔ Got rmarkdown 2.26 (i386+x86_64-w64-mingw32) (2.70 MB)                                       
✔ Got textshaping 0.3.7 (i386+x86_64-w64-mingw32) (1.19 MB)                                    
✔ Got rlistings 0.2.8 (i386+x86_64-w64-mingw32) (3.22 MB)                                      
✔ Got testthat 3.2.1.1 (i386+x86_64-w64-mingw32) (2.23 MB)                                     
✔ Got forcats 1.0.0 (i386+x86_64-w64-mingw32) (429.40 kB)                                      
✔ Got foreach 1.5.2 (i386+x86_64-w64-mingw32) (150.03 kB)                                      
✔ Got colorspace 2.1-0 (i386+x86_64-w64-mingw32) (2.64 MB)                                     
✔ Got globals 0.16.3 (i386+x86_64-w64-mingw32) (110.63 kB)                                     
✔ Got iterators 1.0.14 (i386+x86_64-w64-mingw32) (355.59 kB)                                   
✔ Got jquerylib 0.1.4 (i386+x86_64-w64-mingw32) (526.15 kB)                                    
✔ Got jsonlite 1.8.8 (i386+x86_64-w64-mingw32) (1.11 MB)                                       
✔ Got stringi 1.8.3 (i386+x86_64-w64-mingw32) (15.01 MB)                                       
✔ Got pingr 2.0.3 (i386+x86_64-w64-mingw32) (60.49 kB)                                         
✔ Got pkgbuild 1.4.4 (i386+x86_64-w64-mingw32) (205.26 kB)                                     
✔ Got pkgconfig 2.0.3 (i386+x86_64-w64-mingw32) (23.00 kB)                                     
✔ Got pkgload 1.3.4 (i386+x86_64-w64-mingw32) (182.59 kB)                                      
✔ Got plotly 4.10.4 (i386+x86_64-w64-mingw32) (3.24 MB)                                        
✔ Got scales 1.3.0 (i386+x86_64-w64-mingw32) (721.01 kB)                                       
✔ Got selectr 0.4-2 (i386+x86_64-w64-mingw32) (497.94 kB)                                      
✔ Got shape 1.4.6.1 (i386+x86_64-w64-mingw32) (755.56 kB)                                      
✔ Got shinybusy 0.3.3 (i386+x86_64-w64-mingw32) (624.45 kB)                                    
✔ Got xtable 1.8-4 (i386+x86_64-w64-mingw32) (711.34 kB)                                       
✔ Got yaml 2.3.8 (i386+x86_64-w64-mingw32) (116.77 kB)                                         
✔ Got zip 2.3.1 (i386+x86_64-w64-mingw32) (432.09 kB)                                          
✔ Got cachem 1.0.8 (i386+x86_64-w64-mingw32) (73.54 kB)                                        
✔ Got geeasy 0.1.1 (i386+x86_64-w64-mingw32) (127.54 kB)                                       
✔ Got geeM 0.10.1 (i386+x86_64-w64-mingw32) (82.07 kB)                                         
✔ Got geepack 1.3.10 (i386+x86_64-w64-mingw32) (693.40 kB)                                     
✔ Got shiny 1.8.1.1 (i386+x86_64-w64-mingw32) (4.84 MB)                                       
✔ Got glmnet 4.1-8 (i386+x86_64-w64-mingw32) (2.43 MB)                                
✔ Got processx 3.8.4 (i386+x86_64-w64-mingw32) (685.53 kB)                            
✔ Got ps 1.7.6 (i386+x86_64-w64-mingw32) (555.70 kB)                                  
✔ Got bslib 0.7.0 (i386+x86_64-w64-mingw32) (5.57 MB)                                 
✔ Got promises 1.3.0 (i386+x86_64-w64-mingw32) (2.01 MB)                              
✔ Got tern.mmrm 0.3.0 (i386+x86_64-w64-mingw32) (568.88 kB)                           
✔ Got tinytex 0.50 (i386+x86_64-w64-mingw32) (142.93 kB)                              
✔ Got triebeard 0.4.1 (i386+x86_64-w64-mingw32) (499.03 kB)                           
✔ Got TMB 1.9.11 (i386+x86_64-w64-mingw32) (1.95 MB)                                 
✔ Got highr 0.10 (i386+x86_64-w64-mingw32) (46.92 kB)                       
✔ Got kinship2 1.9.6.1 (i386+x86_64-w64-mingw32) (563.84 kB)                
✔ Got knitr 1.46 (i386+x86_64-w64-mingw32) (1.09 MB)                        
✔ Got hms 1.1.3 (i386+x86_64-w64-mingw32) (105.79 kB)                       
✔ Got fontquiver 0.2.1 (i386+x86_64-w64-mingw32) (2.28 MB)                  
✔ Got later 1.3.2 (i386+x86_64-w64-mingw32) (441.09 kB)                     
✔ Got pillar 1.9.0 (i386+x86_64-w64-mingw32) (663.49 kB)                    
✔ Got praise 1.0.0 (i386+x86_64-w64-mingw32) (20.25 kB)                     
✔ Got R.oo 1.26.0 (i386+x86_64-w64-mingw32) (1.00 MB)                       
✔ Got rvest 1.0.4 (i386+x86_64-w64-mingw32) (309.79 kB)                     
✔ Got shinyjs 2.1.0 (i386+x86_64-w64-mingw32) (1.11 MB)                     
✔ Got Rcpp 1.0.12 (i386+x86_64-w64-mingw32) (2.87 MB)                       
✔ Got teal.widgets 0.4.2 (i386+x86_64-w64-mingw32) (201.66 kB)              
✔ Got sass 0.4.9 (i386+x86_64-w64-mingw32) (2.61 MB)                        
✔ Got teal.transform 0.5.0 (i386+x86_64-w64-mingw32) (2.34 MB)              
✔ Got checkmate 2.3.1 (i386+x86_64-w64-mingw32) (746.81 kB)                 
✔ Got cli 3.6.2 (i386+x86_64-w64-mingw32) (1.36 MB)                         
✔ Got fontBitstreamVera 0.1.1 (i386+x86_64-w64-mingw32) (697.83 kB)         
✔ Got evaluate 0.23 (i386+x86_64-w64-mingw32) (85.94 kB)                    
✔ Got logger 0.3.0 (i386+x86_64-w64-mingw32) (757.59 kB)                   
✔ Got lubridate 1.9.3 (i386+x86_64-w64-mingw32) (989.98 kB)               
✔ Got R6 2.5.1 (i386+x86_64-w64-mingw32) (85.25 kB)                       
✔ Got rappdirs 0.3.3 (i386+x86_64-w64-mingw32) (52.48 kB)                 
✔ Got SparseM 1.81 (i386+x86_64-w64-mingw32) (1.05 MB)                    
✔ Got R.utils 2.12.3 (i386+x86_64-w64-mingw32) (1.46 MB)                  
✔ Got tern.gee 0.1.3 (i386+x86_64-w64-mingw32) (435.96 kB)                
✔ Got timechange 0.3.0 (i386+x86_64-w64-mingw32) (507.92 kB)              
✔ Got bit 4.0.5 (i386+x86_64-w64-mingw32) (1.15 MB)                       
✔ Got tzdb 0.4.0 (i386+x86_64-w64-mingw32) (1.00 MB)                      
✔ Got car 3.1-2 (i386+x86_64-w64-mingw32) (1.73 MB)                       
✔ Got clipr 0.8.0 (i386+x86_64-w64-mingw32) (55.88 kB)                    
✔ Got desc 1.4.3 (i386+x86_64-w64-mingw32) (339.25 kB)                    
✔ Got callr 3.7.6 (i386+x86_64-w64-mingw32) (474.57 kB)                   
✔ Got fs 1.6.3 (i386+x86_64-w64-mingw32) (397.49 kB)                      
✔ Got formatters 0.5.6 (i386+x86_64-w64-mingw32) (4.56 MB)                
✔ Got parallelly 1.37.1 (i386+x86_64-w64-mingw32) (367.60 kB)             
✔ Got lazyeval 0.2.2 (i386+x86_64-w64-mingw32) (162.48 kB)                
✔ Got lifecycle 1.0.4 (i386+x86_64-w64-mingw32) (141.91 kB)               
✔ Got teal.logger 0.2.0 (i386+x86_64-w64-mingw32) (54.20 kB)              
✔ Got teal.reporter 0.3.1 (i386+x86_64-w64-mingw32) (674.21 kB)           
✔ Got lme4 1.1-35.3 (i386+x86_64-w64-mingw32) (4.55 MB)                   
✔ Got openssl 2.1.1 (i386+x86_64-w64-mingw32) (3.18 MB)                   
✔ Got chromote 0.2.0 (i386+x86_64-w64-mingw32) (386.45 kB)                
✔ Got xml2 1.3.6 (i386+x86_64-w64-mingw32) (1.61 MB)                      
✔ Got gdtools 0.3.7 (i386+x86_64-w64-mingw32) (2.19 MB)                   
✔ Got labelled 2.12.0 (i386+x86_64-w64-mingw32) (324.21 kB)               
✔ Got ggrepel 0.9.5 (i386+x86_64-w64-mingw32) (594.13 kB)                 
✔ Got tern 0.9.4 (i386+x86_64-w64-mingw32) (5.61 MB)                      
✔ Got ggridges 0.5.6 (i386+x86_64-w64-mingw32) (2.27 MB)                  
✔ Got sys 3.4.2 (i386+x86_64-w64-mingw32) (46.89 kB)                      
✔ Got shinycssloaders 1.0.0 (i386+x86_64-w64-mingw32) (141.29 kB)         
✔ Got teal.slice 0.5.0 (i386+x86_64-w64-mingw32) (1.68 MB)                
✔ Got teal.data 0.5.0 (i386+x86_64-w64-mingw32) (2.17 MB)                 
✔ Got xfun 0.43 (i386+x86_64-w64-mingw32) (499.55 kB)                     
✔ Got fontawesome 0.5.2 (i386+x86_64-w64-mingw32) (1.35 MB)               
✔ Got httr 1.4.7 (i386+x86_64-w64-mingw32) (497.92 kB)                    
✔ Got styler 1.10.3 (i386+x86_64-w64-mingw32) (864.41 kB)                 
✔ Got tibble 3.2.1 (i386+x86_64-w64-mingw32) (695.40 kB)                  
✔ Got tidyselect 1.2.1 (i386+x86_64-w64-mingw32) (229.99 kB)              
✔ Got fontLiberation 0.1.0 (i386+x86_64-w64-mingw32) (4.53 MB)            
✔ Got tidyr 1.3.1 (i386+x86_64-w64-mingw32) (1.27 MB)                     
✔ Got vistime 1.2.4 (i386+x86_64-w64-mingw32) (2.00 MB)                   
✔ Got rprojroot 2.0.4 (i386+x86_64-w64-mingw32) (115.37 kB)               
✔ Got bit64 4.0.5 (i386+x86_64-w64-mingw32) (501.75 kB)                   
✔ Got rtables 0.6.7 (i386+x86_64-w64-mingw32) (3.83 MB)                   
✔ Got withr 3.0.0 (i386+x86_64-w64-mingw32) (250.88 kB)                   
✔ Got labeling 0.4.3 (i386+x86_64-w64-mingw32) (63.85 kB)                 
✔ Got carData 3.0-5 (i386+x86_64-w64-mingw32) (1.71 MB)                   
✔ Got isoband 0.2.7 (i386+x86_64-w64-mingw32) (1.93 MB)                   
✔ Got purrr 1.0.2 (i386+x86_64-w64-mingw32) (511.30 kB)                   
✔ Got Rdpack 2.6 (i386+x86_64-w64-mingw32) (760.35 kB)                    
✔ Got readr 2.1.5 (i386+x86_64-w64-mingw32) (1.18 MB)                     
✔ Got ggplot2 3.5.0 (i386+x86_64-w64-mingw32) (4.88 MB)                   
✔ Downloaded 188 packages (211.02 MB) in 4m 15.2s                         
✔ Installed abind 1.4-5  (1.2s)                                                       
✔ Installed anytime 0.3.9  (1.5s)                      
✔ Installed askpass 1.2.0  (2.3s)                      
✔ Installed assertthat 0.2.1  (2.5s)                   
✔ Installed backports 1.4.1  (2.8s)                   
✔ Installed base64enc 0.1-3  (3.2s)                   
✔ Installed bit 4.0.5  (3.5s)                         
✔ Installed bit64 4.0.5  (3.9s)                       
✔ Installed brio 1.1.4  (4.3s)                        
✔ Installed broom 1.0.5  (5s)                                                              
✔ Installed cachem 1.0.8  (5.2s)                                                         
✔ Installed bslib 0.7.0  (6s)                                                              
✔ Installed callr 3.7.6  (1.4s)                                                              
✔ Installed car 3.1-2  (1.5s)                         
✔ Installed carData 3.0-5  (2s)                       
✔ Installed checkmate 2.3.1  (2s)                     
✔ Installed chromote 0.2.0  (2.4s)                    
✔ Installed cli 3.6.2  (2.7s)                         
✔ Installed clipr 0.8.0  (3.2s)                        
✔ Installed commonmark 1.9.1  (3s)                     
✔ Installed colorspace 2.1-0  (3.9s)                   
✔ Installed cowplot 1.1.3  (4s)                        
✔ Installed crayon 1.5.2  (4s)                         
✔ Installed crosstalk 1.2.1  (4.4s)                    
✔ Installed crul 1.4.2  (4.6s)                         
✔ Installed curl 5.2.1  (5.3s)                         
✔ Installed desc 1.4.3  (5.1s)                         
✔ Installed data.table 1.15.4  (5.8s)                  
✔ Installed diffobj 0.3.5  (5.8s)                      
✔ Installed digest 0.6.35  (6.2s)                      
✔ Installed dplyr 1.1.4  (6.3s)                        
✔ Installed ellipsis 0.3.2  (6.3s)                     
✔ Installed DT 0.33  (7.4s)                            
✔ Installed emmeans 1.10.1  (6.8s)                     
✔ Installed estimability 1.5  (7.1s)                   
✔ Installed evaluate 0.23  (6.9s)                      
✔ Installed fansi 1.0.6  (6.9s)                        
✔ Installed farver 2.1.1  (6.7s)                       
✔ Installed fastmap 1.1.1  (6.8s)                      
✔ Installed flextable 0.9.5  (6.9s)                    
✔ Installed fontawesome 0.5.2  (6.9s)                  
✔ Installed generics 0.1.3  (274ms)                    
✔ Installed fontBitstreamVera 0.1.1  (7.5s)            
✔ Installed fontLiberation 0.1.0  (7.5s)               
✔ Installed fontquiver 0.2.1  (7.4s)                   
✔ Installed ggrepel 0.9.5  (245ms)                     
✔ Installed forcats 1.0.0  (7.8s)                      
✔ Installed foreach 1.5.2  (7.8s)                      
✔ Installed formatters 0.5.6  (7.5s)                   
✔ Installed fs 1.6.3  (7.7s)                           
✔ Installed gdtools 0.3.7  (7.5s)                      
✔ Installed geeasy 0.1.1  (7.5s)                       
✔ Installed geeM 0.10.1  (7.5s)                        
✔ Installed geepack 1.3.10  (7.3s)                     
✔ Installed gfonts 0.2.0  (6.5s)                       
✔ Installed ggformula 0.12.0  (6.6s)                   
✔ Installed ggplot2 3.5.0  (6.5s)                      
✔ Installed ggridges 0.5.6  (5.9s)                     
✔ Installed glmnet 4.1-8  (5.9s)                       
✔ Installed globals 0.16.3  (6.2s)                     
✔ Installed glue 1.7.0  (6.2s)                         
✔ Installed gridExtra 2.3  (6.1s)                      
✔ Installed gtable 0.3.4  (6.1s)                       
✔ Installed haven 2.5.4  (6.1s)                        
✔ Installed highr 0.10  (6.1s)                         
✔ Installed hms 1.1.3  (6.2s)                          
✔ Installed htmltools 0.5.8.1  (6.1s)                  
✔ Installed htmlwidgets 1.6.4  (6s)                    
✔ Installed httpcode 0.3.0  (6.1s)                     
✔ Installed httpuv 1.6.15  (6s)                        
✔ Installed lifecycle 1.0.4  (249ms)                   
✔ Installed httr 1.4.7  (6.6s)                         
✔ Installed isoband 0.2.7  (6.1s)                      
✔ Installed iterators 1.0.14  (6.1s)                   
✔ Installed jquerylib 0.1.4  (6.1s)                    
✔ Installed jsonlite 1.8.8  (6s)                       
✔ Installed kinship2 1.9.6.1  (6s)                     
✔ Installed knitr 1.46  (6.2s)                         
✔ Installed labeling 0.4.3  (6.1s)                     
✔ Installed labelled 2.12.0  (6.1s)                    
✔ Installed later 1.3.2  (6.1s)                        
✔ Installed lazyeval 0.2.2  (6.2s)                     
✔ Installed mosaicCore 0.9.4.0  (480ms)                
✔ Installed lme4 1.1-35.3  (5.9s)                      
✔ Installed logger 0.3.0  (5.9s)                       
✔ Installed lubridate 1.9.3  (6s)                      
✔ Installed magrittr 2.0.3  (6.1s)                     
✔ Installed MatrixModels 0.5-3  (6.1s)                 
✔ Installed memoise 2.0.1  (6.3s)                      
✔ Installed MESS 0.5.12  (6.2s)                        
✔ Installed mime 0.12  (6s)                             
✔ Installed minqa 1.2.6  (6s)                           
✔ Installed mmrm 0.3.11  (6.1s)                         
✔ Installed munsell 0.5.1  (5.6s)                       
✔ Installed mvtnorm 1.2-4  (5.6s)                       
✔ Installed nestcolor 0.1.2  (5.5s)                     
✔ Installed nloptr 2.0.3  (5.6s)                        
✔ Installed numDeriv 2016.8-1.1  (5.9s)                 
✔ Installed officer 0.6.5  (5.8s)                       
✔ Installed openssl 2.1.1  (5.8s)                       
✔ Installed parallelly 1.37.1  (5.6s)                   
✔ Installed pbkrtest 0.5.2  (5.6s)                      
✔ Installed pillar 1.9.0  (5.6s)                        
✔ Installed pingr 2.0.3  (5.5s)                         
✔ Installed pkgbuild 1.4.4  (5.5s)                      
✔ Installed pkgconfig 2.0.3  (5.1s)                     
✔ Installed pkgload 1.3.4  (5.2s)                       
✔ Installed plotly 4.10.4  (5.2s)                       
✔ Installed praise 1.0.0  (5.1s)                        
✔ Installed processx 3.8.4  (5.2s)                      
✔ Installed promises 1.3.0  (5.3s)                      
✔ Installed ps 1.7.6  (5.2s)                            
✔ Installed purrr 1.0.2  (5.3s)                         
✔ Installed quadprog 1.5-8  (5.3s)                      
✔ Installed quantreg 5.97  (5.9s)                       
✔ Installed R.cache 0.16.0  (5.9s)                      
✔ Installed R.methodsS3 1.8.2  (5.9s)                   
✔ Installed R.oo 1.26.0  (6s)                           
✔ Installed R.utils 2.12.3  (6s)                        
✔ Installed R6 2.5.1  (6s)                              
✔ Installed ragg 1.3.0  (6.2s)                          
✔ Installed rappdirs 0.3.3  (6.2s)                      
✔ Installed rbibutils 2.2.16  (6.1s)                    
✔ Installed RColorBrewer 1.1-3  (6.2s)                  
✔ Installed Rdpack 2.6  (5.8s)                          
✔ Installed readr 2.1.5  (5.1s)                         
✔ Installed rematch2 2.1.2  (5.1s)                      
✔ Installed rlang 1.1.3  (5.1s)                         
✔ Installed Rcpp 1.0.12  (8.2s)                         
✔ Installed rlistings 0.2.8  (5.7s)                     
✔ Installed rmarkdown 2.26  (5.6s)                      
✔ Installed rprojroot 2.0.4  (5.6s)                     
✔ Installed rtables 0.6.7  (5.4s)                       
✔ Installed rvest 1.0.4  (5.4s)                         
✔ Installed sass 0.4.9  (5.4s)                          
✔ Installed scales 1.3.0  (5.3s)                        
✔ Installed selectr 0.4-2  (5.3s)                       
✔ Installed shape 1.4.6.1  (5.4s)                       
✔ Installed shiny 1.8.1.1  (5.5s)                       
✔ Installed shinybusy 0.3.3  (5.2s)                     
✔ Installed shinycssloaders 1.0.0  (5.1s)               
✔ Installed shinyjs 2.1.0  (5.1s)                       
✔ Installed shinytest2 0.3.1  (5s)                      
✔ Installed shinyvalidate 0.1.3  (5s)                   
✔ Installed sourcetools 0.1.7-1  (4.5s)                 
✔ Installed SparseM 1.81  (4.4s)                        
✔ Installed shinyWidgets 0.8.5  (5.9s)                  
✔ Installed stringi 1.8.3  (4.9s)                       
✔ Installed stringr 1.5.1  (5s)                         
✔ Installed styler 1.10.3  (4.8s)                       
✔ Installed sys 3.4.2  (4.8s)                           
✔ Installed systemfonts 1.0.6  (4.8s)                   
✔ Installed teal 0.15.2  (4.9s)                         
✔ Installed teal.code 0.5.0  (4.8s)                     
✔ Installed teal.data 0.5.0  (5s)                       
✔ Installed teal.logger 0.2.0  (5.1s)                   
✔ Installed teal.reporter 0.3.1  (5s)                   
✔ Installed teal.slice 0.5.0  (5s)                      
✔ Installed teal.transform 0.5.0  (4.8s)                
✔ Installed teal.widgets 0.4.2  (4.9s)                  
✔ Installed tern 0.9.4  (4.8s)                          
✔ Installed tern.gee 0.1.3  (5s)                        
✔ Installed tern.mmrm 0.3.0  (5s)                       
✔ Installed testthat 3.2.1.1  (5.1s)                    
✔ Installed textshaping 0.3.7  (5.1s)                   
✔ Installed tibble 3.2.1  (5.1s)                        
✔ Installed tidyr 1.3.1  (5s)                           
✔ Installed tidyselect 1.2.1  (5s)                      
✔ Installed timechange 0.3.0  (5.1s)                    
✔ Installed tinytex 0.50  (5.1s)                        
✔ Installed waldo 0.5.2  (479ms)                        
✔ Installed TMB 1.9.11  (5.5s)                          
✔ Installed triebeard 0.4.1  (5.5s)                     
✔ Installed tzdb 0.4.0  (5.5s)                          
✔ Installed urltools 1.7.3  (5.4s)                      
✔ Installed utf8 1.2.4  (5.3s)                          
✔ Installed uuid 1.2-0  (5.5s)                          
✔ Installed vctrs 0.6.5  (5.6s)                         
✔ Installed viridisLite 0.4.2  (5.4s)                   
✔ Installed vistime 1.2.4  (5.5s)                      
✔ Installed vroom 1.6.5  (5.5s)                        
✔ Installed websocket 1.4.1  (4.8s)                    
✔ Installed withr 3.0.0  (5s)                          
✔ Installed xfun 0.43  (5.1s)                                                                  
✔ Installed xml2 1.3.6  (5s)                                                                 
✔ Installed xtable 1.8-4  (4.9s)                                                       
✔ Installed yaml 2.3.8  (4.8s)                                                   
✔ Installed zip 2.3.1  (4.7s)                                            
── R CMD build ───────────────────────────────────────────────────────────────────────────────
pdflatex not found! Not building PDF manual.
✔  checking for file 'C:\Rprojects\teal.modules.clinical/DESCRIPTION' ...
─  preparing 'teal.modules.clinical': (31.9s)
✔  checking DESCRIPTION meta-information ... 
─  installing the package to build vignettes (2s)
✔  creating vignettes (26.5s)
─  checking for LF line-endings in source and make files and shell scripts (2.4s)
─  checking for empty or unneeded directories
   Removed empty directory 'teal.modules.clinical/Include'
─  building 'teal.modules.clinical_0.9.1.9006.tar.gz'
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     'teal.modules.clinical/Lib/site-packages/setuptools/config/_validate_pyproject/fastjsonschema_exceptions.py'
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     'teal.modules.clinical/Lib/site-packages/setuptools/config/_validate_pyproject/fastjsonschema_validations.py'
   
── R CMD check ───────────────────────────────────────────────────────────────────────────────
─  using log directory 'C:/Users/kosinsm4/AppData/Local/Temp/RtmpkZuXze/file5ebc110f7f05/teal.modules.clinical.Rcheck' (503ms)
─  using R version 4.4.0 (2024-04-24 ucrt)
─  using platform: x86_64-w64-mingw32
─  R was compiled by
       gcc.exe (GCC) 13.2.0
       GNU Fortran (GCC) 13.2.0
─  running under: Windows 11 x64 (build 22621)
─  using session charset: UTF-8
✔  checking for file 'teal.modules.clinical/DESCRIPTION' (4.1s)
─  this is package 'teal.modules.clinical' version '0.9.1.9006'
─  package encoding: UTF-8
✔  checking package namespace information ...
✔  checking package dependencies (1.7s)
✔  checking if this is a source package ... 
✔  checking if there is a namespace
W  checking for executable files (29.9s)
   Found the following executable files:
     Lib/site-packages/pip/_vendor/distlib/t32.exe
     Lib/site-packages/pip/_vendor/distlib/t64-arm.exe
     Lib/site-packages/pip/_vendor/distlib/t64.exe
     Lib/site-packages/pip/_vendor/distlib/w32.exe
     Lib/site-packages/pip/_vendor/distlib/w64-arm.exe
     Lib/site-packages/pip/_vendor/distlib/w64.exe
     Lib/site-packages/setuptools/cli-32.exe
     Lib/site-packages/setuptools/cli-64.exe
     Lib/site-packages/setuptools/cli-arm64.exe
     Lib/site-packages/setuptools/cli.exe
     Lib/site-packages/setuptools/gui-32.exe
     Lib/site-packages/setuptools/gui-64.exe
     Lib/site-packages/setuptools/gui-arm64.exe
     Lib/site-packages/setuptools/gui.exe
     Scripts/pip-3.11.exe
     Scripts/pip.exe
     Scripts/pip3.11.exe
     Scripts/pip3.exe
     Scripts/python.exe
     Scripts/pythonw.exe
     Scripts/wheel-3.11.exe
     Scripts/wheel.exe
     Scripts/wheel3.11.exe
     Scripts/wheel3.exe
   Source packages should not contain undeclared executable files.
   See section 'Package structure' in the 'Writing R Extensions' manual.
✔  checking for hidden files and directories ... 
W  checking for portable file names ... 
   Found the following files with non-portable file names:
     Lib/site-packages/setuptools/command/launcher manifest.xml
     Lib/site-packages/setuptools/script (dev).tmpl
   These are not fully portable file names.
   See section 'Package structure' in the 'Writing R Extensions' manual.
   Found the following non-portable file paths:
     teal.modules.clinical/Lib/site-packages/setuptools/config/_validate_pyproject/fastjsonschema_exceptions.py
     teal.modules.clinical/Lib/site-packages/setuptools/config/_validate_pyproject/fastjsonschema_validations.py
   
   Tarballs are only required to store paths of up to 100 bytes and cannot
   store those of more than 256 bytes, with restrictions including to 100
   bytes for the final component.
   See section 'Package structure' in the 'Writing R Extensions' manual.
✔  checking whether package 'teal.modules.clinical' can be installed (16.4s)
✔  checking installed package size (1.3s)
✔  checking package directory
✔  checking 'build' directory
✔  checking DESCRIPTION meta-information ... 
✔  checking top-level files
✔  checking for left-over files ...
✔  checking index information ... 
✔  checking package subdirectories (1.4s)
✔  checking code files for non-ASCII characters ... 
✔  checking R files for syntax errors ... 
✔  checking whether the package can be loaded (2s)
✔  checking whether the package can be loaded with stated dependencies (2.1s)
✔  checking whether the package can be unloaded cleanly (2s)
✔  checking whether the namespace can be loaded with stated dependencies (1.8s)
✔  checking whether the namespace can be unloaded cleanly (2.1s)
✔  checking loading without being on the library search path (2.4s)
✔  checking whether startup messages can be suppressed (4.1s)
✔  checking dependencies in R code (3.2s)
✔  checking S3 generic/method consistency (2s)
✔  checking replacement functions (1.9s)
✔  checking foreign function calls (2.7s)
✔  checking R code for possible problems (13.6s)
✔  checking Rd files (2.1s)
✔  checking Rd metadata ... 
✔  checking Rd cross-references (552ms)
✔  checking for missing documentation entries (2.1s)
✔  checking for code/documentation mismatches (6.5s)
✔  checking Rd \usage sections (2.9s)
✔  checking Rd contents (666ms)
✔  checking for unstated dependencies in examples (1.8s)
✔  checking contents of 'data' directory ... 
✔  checking data for non-ASCII characters (442ms)
✔  checking LazyData
✔  checking data for ASCII and uncompressed saves ... 
✔  checking installed files from 'inst/doc' (464ms)
✔  checking files in 'vignettes' ... 
✔  checking examples (10.3s)
✔  checking for unstated dependencies in 'tests' ... 
─  checking tests (428ms)
✔  Running 'testthat.R' (17.1s)
✔  checking for unstated dependencies in vignettes (558ms)
✔  checking package vignettes ... 
✔  checking re-building of vignette outputs (13.4s)
W  checking PDF version of manual (4.6s)
   LaTeX errors when creating PDF version.
   This typically indicates Rd problems.
E  checking PDF version of manual without index (4.1s)
   Re-running with no redirection of stdout/stderr.
   Hmm ... looks like a package
   Converting parsed Rd's to LaTeX ...........
   Creating pdf output from LaTeX ...
   Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
     pdflatex is not available
   Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
     pdflatex is not available
   Error in running tools::texi2pdf()
   You may want to clean up by 'rm -Rf C:/Users/kosinsm4/AppData/Local/Temp/RtmpaSmdmg/Rd2pdfb005fdf22c7'
   
   See
     'C:/Users/kosinsm4/AppData/Local/Temp/RtmpkZuXze/file5ebc110f7f05/teal.modules.clinical.Rcheck/00check.log'
   for details.
```

**Comment by m7pr** [comment]
Ok I run this with LaTeX installed and worked

```r
verdepcheck::min_cohort_deps_check(".")
✔ Updated metadata database: 2.20 MB in 2 files.
✔ Updating metadata database ... done
ℹ Creating temporary DESCRIPTION file: C:\Users\kosinsm4\AppData\Local\Temp\Rtmp84khcL\file97c30f66fb7
ℹ Creating library directory: C:\Users\kosinsm4\AppData\Local\Temp\Rtmp84khcL\file97c54d8598f
✔ Loading metadata database ... done
ℹ Getting 180 pkgs (185.16 MB), 8 (25.09 MB) cached                  
✔ Cached copy of abind 1.4-5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of anytime 0.3.9 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of askpass 1.2.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of assertthat 0.2.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of backports 1.4.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of base64enc 0.1-3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of bit 4.0.5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of bit64 4.0.5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of brio 1.1.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of broom 1.0.5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of bslib 0.7.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of cachem 1.0.8 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of callr 3.7.6 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of car 3.1-2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of carData 3.0-5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of checkmate 2.3.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of chromote 0.2.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of cli 3.6.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of clipr 0.8.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of colorspace 2.1-0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of commonmark 1.9.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of cowplot 1.1.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of crayon 1.5.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of crosstalk 1.2.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of curl 5.2.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of data.table 1.15.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of desc 1.4.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of diffobj 0.3.5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of digest 0.6.35 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of dplyr 1.1.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of DT 0.33 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of ellipsis 0.3.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of emmeans 1.10.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of estimability 1.5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of evaluate 0.23 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of fansi 1.0.6 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of farver 2.1.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of fastmap 1.1.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of flextable 0.9.5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of fontawesome 0.5.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of fontBitstreamVera 0.1.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of fontLiberation 0.1.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of fontquiver 0.2.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of forcats 1.0.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of foreach 1.5.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of fs 1.6.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of gdtools 0.3.7 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of geeasy 0.1.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of geeM 0.10.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of geepack 1.3.10 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of generics 0.1.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of gfonts 0.2.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of ggformula 0.12.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of ggplot2 3.5.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of ggrepel 0.9.5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of ggridges 0.5.6 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of glmnet 4.1-8 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of globals 0.16.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of glue 1.7.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of gridExtra 2.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of gtable 0.3.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of haven 2.5.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of highr 0.10 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of hms 1.1.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of htmltools 0.5.8.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of htmlwidgets 1.6.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of httpcode 0.3.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of httpuv 1.6.15 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of httr 1.4.7 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of isoband 0.2.7 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of iterators 1.0.14 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of jquerylib 0.1.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of jsonlite 1.8.8 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of kinship2 1.9.6.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of knitr 1.46 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of labeling 0.4.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of labelled 2.12.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of later 1.3.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of lazyeval 0.2.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of lifecycle 1.0.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of logger 0.3.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of lubridate 1.9.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of magrittr 2.0.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of MatrixModels 0.5-3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of memoise 2.0.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of MESS 0.5.12 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of mime 0.12 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of minqa 1.2.6 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of mmrm 0.3.11 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of mosaicCore 0.9.4.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of munsell 0.5.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of mvtnorm 1.2-4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of nestcolor 0.1.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of nloptr 2.0.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of numDeriv 2016.8-1.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of officer 0.6.5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of openssl 2.1.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of parallelly 1.37.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of pbkrtest 0.5.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of pillar 1.9.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of pingr 2.0.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of pkgbuild 1.4.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of pkgconfig 2.0.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of pkgload 1.3.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of plotly 4.10.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of praise 1.0.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of processx 3.8.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of promises 1.3.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of ps 1.7.6 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of purrr 1.0.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of quadprog 1.5-8 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of quantreg 5.97 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of R.cache 0.16.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of R.methodsS3 1.8.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of R.oo 1.26.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of R.utils 2.12.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of R6 2.5.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of ragg 1.3.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of rappdirs 0.3.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of rbibutils 2.2.16 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of RColorBrewer 1.1-3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of Rcpp 1.0.12 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of Rdpack 2.6 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of readr 2.1.5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of rematch2 2.1.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of rlang 1.1.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of rmarkdown 2.26 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of rprojroot 2.0.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of rvest 1.0.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of sass 0.4.9 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of scales 1.3.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of selectr 0.4-2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of shape 1.4.6.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of shiny 1.8.1.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of shinybusy 0.3.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of shinycssloaders 1.0.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of shinyjs 2.1.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of shinytest2 0.3.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of shinyvalidate 0.1.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of sourcetools 0.1.7-1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of SparseM 1.81 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of stringi 1.8.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of stringr 1.5.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of styler 1.10.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of sys 3.4.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of systemfonts 1.0.6 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of teal 0.15.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of teal.code 0.5.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of teal.data 0.5.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of teal.logger 0.2.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of teal.reporter 0.3.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of teal.slice 0.5.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of teal.transform 0.5.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of teal.widgets 0.4.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of tern.gee 0.1.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of tern.mmrm 0.3.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of textshaping 0.3.7 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of tibble 3.2.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of tidyr 1.3.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of tidyselect 1.2.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of timechange 0.3.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of tinytex 0.50 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of TMB 1.9.11 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of triebeard 0.4.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of tzdb 0.4.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of urltools 1.7.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of utf8 1.2.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of uuid 1.2-0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of vctrs 0.6.5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of viridisLite 0.4.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of vistime 1.2.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of vroom 1.6.5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of waldo 0.5.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of websocket 1.4.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of withr 3.0.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of xfun 0.43 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of xml2 1.3.6 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of xtable 1.8-4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of yaml 2.3.8 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of zip 2.3.1 (i386+x86_64-w64-mingw32) is the latest build
✔ No downloads needed, all packages are cached                       
✔ Installed abind 1.4-5  (715ms)                       
✔ Installed anytime 0.3.9  (866ms)                     
✔ Installed askpass 1.2.0  (1.2s)                      
✔ Installed assertthat 0.2.1  (1.3s)                   
✔ Installed backports 1.4.1  (1.6s)                   
✔ Installed base64enc 0.1-3  (1.8s)                   
✔ Installed bit 4.0.5  (2s)                           
✔ Installed bit64 4.0.5  (2.3s)                       
✔ Installed brio 1.1.4  (2.5s)                        
✔ Installed broom 1.0.5  (2.8s)                       
✔ Installed cachem 1.0.8  (3s)                        
✔ Installed bslib 0.7.0  (3.5s)                       
✔ Installed callr 3.7.6  (974ms)                      
✔ Installed car 3.1-2  (1.1s)                         
✔ Installed clipr 0.8.0  (430ms)                      
✔ Installed carData 3.0-5  (1.6s)                     
✔ Installed checkmate 2.3.1  (1.6s)                   
✔ Installed commonmark 1.9.1  (400ms)                 
✔ Installed chromote 0.2.0  (2.1s)                    
✔ Installed cli 3.6.2  (2.1s)                         
✔ Installed crayon 1.5.2  (368ms)                     
✔ Installed colorspace 2.1-0  (1.9s)                  
✔ Installed cowplot 1.1.3  (1.6s)                     
✔ Installed crosstalk 1.2.1  (1.2s)                   
✔ Installed crul 1.4.2  (1.2s)                        
✔ Installed curl 5.2.1  (1.7s)                        
✔ Installed desc 1.4.3  (1.6s)                        
✔ Installed data.table 1.15.4  (2.3s)                 
✔ Installed diffobj 0.3.5  (2.4s)                     
✔ Installed digest 0.6.35  (2.3s)                     
✔ Installed dplyr 1.1.4  (2.6s)                       
✔ Installed ellipsis 0.3.2  (2.6s)                     
✔ Installed fontawesome 0.5.2  (621ms)                 
✔ Installed estimability 1.5  (3s)                     
✔ Installed DT 0.33  (4s)                              
✔ Installed emmeans 1.10.1  (4s)                       
✔ Installed evaluate 0.23  (3.7s)                      
✔ Installed fansi 1.0.6  (3.6s)                        
✔ Installed farver 2.1.1  (3.7s)                       
✔ Installed geeM 0.10.1  (154ms)                       
✔ Installed fastmap 1.1.1  (4.2s)                      
✔ Installed generics 0.1.3  (153ms)                    
✔ Installed flextable 0.9.5  (4.7s)                    
✔ Installed fontBitstreamVera 0.1.1  (4.2s)            
✔ Installed fontLiberation 0.1.0  (4.5s)               
✔ Installed fontquiver 0.2.1  (4.5s)                   
✔ Installed forcats 1.0.0  (4.8s)                      
✔ Installed foreach 1.5.2  (4.9s)                      
✔ Installed formatters 0.5.6  (5.1s)                   
✔ Installed fs 1.6.3  (5.2s)                           
✔ Installed gdtools 0.3.7  (5.2s)                      
✔ Installed geeasy 0.1.1  (5.4s)                       
✔ Installed haven 2.5.4  (211ms)                       
✔ Installed geepack 1.3.10  (5.5s)                     
✔ Installed gfonts 0.2.0  (5.1s)                       
✔ Installed ggformula 0.12.0  (5.1s)                   
✔ Installed ggplot2 3.5.0  (5.1s)                      
✔ Installed ggrepel 0.9.5  (5s)                        
✔ Installed ggridges 0.5.6  (4.9s)                     
✔ Installed glmnet 4.1-8  (4.9s)                       
✔ Installed globals 0.16.3  (4.9s)                     
✔ Installed glue 1.7.0  (4.9s)                         
✔ Installed gridExtra 2.3  (4.9s)                      
✔ Installed gtable 0.3.4  (5s)                         
✔ Installed highr 0.10  (4.5s)                         
✔ Installed hms 1.1.3  (4.6s)                          
✔ Installed labeling 0.4.3  (218ms)                    
✔ Installed htmltools 0.5.8.1  (4.9s)                  
✔ Installed htmlwidgets 1.6.4  (4.8s)                  
✔ Installed httpcode 0.3.0  (4.8s)                     
✔ Installed httpuv 1.6.15  (4.8s)                      
✔ Installed httr 1.4.7  (4.9s)                         
✔ Installed isoband 0.2.7  (4.9s)                      
✔ Installed iterators 1.0.14  (4.7s)                   
✔ Installed jquerylib 0.1.4  (4.8s)                    
✔ Installed jsonlite 1.8.8  (4.7s)                     
✔ Installed kinship2 1.9.6.1  (4.7s)                   
✔ Installed knitr 1.46  (4.7s)                         
✔ Installed labelled 2.12.0  (4.3s)                    
✔ Installed later 1.3.2  (4.3s)                        
✔ Installed lazyeval 0.2.2  (4.3s)                     
✔ Installed mosaicCore 0.9.4.0  (140ms)                
✔ Installed lifecycle 1.0.4  (4.6s)                    
✔ Installed lme4 1.1-35.3  (4.6s)                      
✔ Installed nestcolor 0.1.2  (203ms)                   
✔ Installed logger 0.3.0  (4.9s)                       
✔ Installed lubridate 1.9.3  (4.9s)                    
✔ Installed magrittr 2.0.3  (4.9s)                     
✔ Installed MatrixModels 0.5-3  (4.9s)                 
✔ Installed memoise 2.0.1  (4.9s)                      
✔ Installed MESS 0.5.12  (4.9s)                         
✔ Installed mime 0.12  (4.9s)                           
✔ Installed minqa 1.2.6  (4.9s)                         
✔ Installed mmrm 0.3.11  (4.9s)                         
✔ Installed munsell 0.5.1  (4.7s)                       
✔ Installed mvtnorm 1.2-4  (4.8s)                       
✔ Installed nloptr 2.0.3  (4.4s)                        
✔ Installed numDeriv 2016.8-1.1  (4.4s)                 
✔ Installed officer 0.6.5  (4.5s)                       
✔ Installed openssl 2.1.1  (4.4s)                       
✔ Installed parallelly 1.37.1  (4.4s)                   
✔ Installed pbkrtest 0.5.2  (4.4s)                      
✔ Installed pillar 1.9.0  (4.3s)                        
✔ Installed pingr 2.0.3  (4.5s)                         
✔ Installed pkgbuild 1.4.4  (4.5s)                      
✔ Installed pkgconfig 2.0.3  (4.6s)                     
✔ Installed pkgload 1.3.4  (4.5s)                       
✔ Installed plotly 4.10.4  (4.5s)                       
✔ Installed praise 1.0.0  (4.5s)                        
✔ Installed processx 3.8.4  (4.6s)                      
✔ Installed promises 1.3.0  (4.6s)                      
✔ Installed rappdirs 0.3.3  (430ms)                     
✔ Installed ps 1.7.6  (5s)                              
✔ Installed RColorBrewer 1.1-3  (449ms)                 
✔ Installed purrr 1.0.2  (5.2s)                         
✔ Installed quadprog 1.5-8  (5.4s)                      
✔ Installed quantreg 5.97  (5.7s)                       
✔ Installed R.cache 0.16.0  (5.6s)                      
✔ Installed R.methodsS3 1.8.2  (5.5s)                   
✔ Installed R.oo 1.26.0  (5.6s)                         
✔ Installed R.utils 2.12.3  (5.6s)                      
✔ Installed R6 2.5.1  (5.6s)                            
✔ Installed ragg 1.3.0  (5.6s)                          
✔ Installed rbibutils 2.2.16  (5s)                      
✔ Installed Rdpack 2.6  (4.3s)                          
✔ Installed rematch2 2.1.2  (4s)                        
✔ Installed readr 2.1.5  (5s)                           
✔ Installed rlang 1.1.3  (4.4s)                         
✔ Installed Rcpp 1.0.12  (6.5s)                         
✔ Installed rlistings 0.2.8  (4.9s)                     
✔ Installed rmarkdown 2.26  (4.9s)                      
✔ Installed rprojroot 2.0.4  (4.8s)                     
✔ Installed rtables 0.6.7  (4.9s)                       
✔ Installed rvest 1.0.4  (5.1s)                         
✔ Installed sass 0.4.9  (5.2s)                          
✔ Installed scales 1.3.0  (5.2s)                        
✔ Installed selectr 0.4-2  (5.2s)                       
✔ Installed shape 1.4.6.1  (5.3s)                       
✔ Installed shiny 1.8.1.1  (5.3s)                       
✔ Installed shinybusy 0.3.3  (5.2s)                     
✔ Installed systemfonts 1.0.6  (263ms)                  
✔ Installed shinycssloaders 1.0.0  (5.6s)               
✔ Installed shinyjs 2.1.0  (5.6s)                       
✔ Installed shinytest2 0.3.1  (5.6s)                    
✔ Installed shinyvalidate 0.1.3  (5.7s)                 
✔ Installed shinyWidgets 0.8.5  (5.9s)                  
✔ Installed sourcetools 0.1.7-1  (5.7s)                 
✔ Installed SparseM 1.81  (5.7s)                        
✔ Installed stringi 1.8.3  (5.7s)                       
✔ Installed stringr 1.5.1  (5.7s)                       
✔ Installed styler 1.10.3  (5.7s)                       
✔ Installed sys 3.4.2  (5.8s)                           
✔ Installed teal 0.15.2  (5.4s)                         
✔ Installed teal.code 0.5.0  (5.4s)                     
✔ Installed teal.data 0.5.0  (5.6s)                     
✔ Installed teal.logger 0.2.0  (5.6s)                   
✔ Installed teal.reporter 0.3.1  (5.5s)                 
✔ Installed teal.slice 0.5.0  (5.4s)                    
✔ Installed teal.transform 0.5.0  (5.2s)                
✔ Installed tinytex 0.50  (409ms)                       
✔ Installed teal.widgets 0.4.2  (5.4s)                  
✔ Installed triebeard 0.4.1  (311ms)                    
✔ Installed tern 0.9.4  (6s)                            
✔ Installed tern.gee 0.1.3  (6.1s)                      
✔ Installed tern.mmrm 0.3.0  (6.1s)                     
✔ Installed testthat 3.2.1.1  (6.2s)                    
✔ Installed textshaping 0.3.7  (6.1s)                   
✔ Installed tibble 3.2.1  (6s)                          
✔ Installed tidyr 1.3.1  (5.9s)                         
✔ Installed waldo 0.5.2  (219ms)                        
✔ Installed tidyselect 1.2.1  (6.4s)                    
✔ Installed timechange 0.3.0  (6.6s)                    
✔ Installed TMB 1.9.11  (5.9s)                          
✔ Installed tzdb 0.4.0  (5.4s)                          
✔ Installed urltools 1.7.3  (5.5s)                      
✔ Installed utf8 1.2.4  (5.9s)                          
✔ Installed uuid 1.2-0  (5.9s)                          
✔ Installed vctrs 0.6.5  (5.6s)                         
✔ Installed viridisLite 0.4.2  (5.5s)                   
✔ Installed vistime 1.2.4  (5.5s)                      
✔ Installed vroom 1.6.5  (5.4s)                        
✔ Installed websocket 1.4.1  (4.9s)                    
✔ Installed withr 3.0.0  (4.8s)                        
✔ Installed xfun 0.43  (4.7s)                          
✔ Installed xml2 1.3.6  (4.7s)                         
✔ Installed xtable 1.8-4  (4.5s)                       
✔ Installed yaml 2.3.8  (4.3s)                         
✔ Installed zip 2.3.1  (4.3s)                                        
── R CMD build ───────────────────────────────────────────────────── 
✔  checking for file 'C:\Rprojects\teal.modules.clinical/DESCRIPTION'
─  preparing 'teal.modules.clinical': (8.2s)
✔  checking DESCRIPTION meta-information ... 
─  installing the package to build vignettes (2.2s)
✔  creating vignettes (22.5s)
─  checking for LF line-endings in source and make files and shell scripts (3.6s)
─  checking for empty or unneeded directories
   Removed empty directory 'teal.modules.clinical/Include'
─  building 'teal.modules.clinical_0.9.1.9006.tar.gz'
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     'teal.modules.clinical/Lib/site-packages/setuptools/config/_validate_pyproject/fastjsonschema_exceptions.py'
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     'teal.modules.clinical/Lib/site-packages/setuptools/config/_validate_pyproject/fastjsonschema_validations.py'
   
── R CMD check ─────────────────────────────────────────────────────
─  using log directory 'C:/Users/kosinsm4/AppData/Local/Temp/Rtmp84khcL/file97c14113ad9/teal.modules.clinical.Rcheck' (455ms)
─  using R version 4.4.0 (2024-04-24 ucrt)
─  using platform: x86_64-w64-mingw32
─  R was compiled by
       gcc.exe (GCC) 13.2.0
       GNU Fortran (GCC) 13.2.0
─  running under: Windows 11 x64 (build 22621)
─  using session charset: UTF-8
✔  checking for file 'teal.modules.clinical/DESCRIPTION' (2.3s)
─  this is package 'teal.modules.clinical' version '0.9.1.9006'
─  package encoding: UTF-8
✔  checking package namespace information ...
✔  checking package dependencies (1s)
✔  checking if this is a source package ...
✔  checking if there is a namespace
W  checking for executable files (28.1s)
   Found the following executable files:
     Lib/site-packages/pip/_vendor/distlib/t32.exe
     Lib/site-packages/pip/_vendor/distlib/t64-arm.exe
     Lib/site-packages/pip/_vendor/distlib/t64.exe
     Lib/site-packages/pip/_vendor/distlib/w32.exe
     Lib/site-packages/pip/_vendor/distlib/w64-arm.exe
     Lib/site-packages/pip/_vendor/distlib/w64.exe
     Lib/site-packages/setuptools/cli-32.exe
     Lib/site-packages/setuptools/cli-64.exe
     Lib/site-packages/setuptools/cli-arm64.exe
     Lib/site-packages/setuptools/cli.exe
     Lib/site-packages/setuptools/gui-32.exe
     Lib/site-packages/setuptools/gui-64.exe
     Lib/site-packages/setuptools/gui-arm64.exe
     Lib/site-packages/setuptools/gui.exe
     Scripts/pip-3.11.exe
     Scripts/pip.exe
     Scripts/pip3.11.exe
     Scripts/pip3.exe
     Scripts/python.exe
     Scripts/pythonw.exe
     Scripts/wheel-3.11.exe
     Scripts/wheel.exe
     Scripts/wheel3.11.exe
     Scripts/wheel3.exe
   Source packages should not contain undeclared executable files.
   See section 'Package structure' in the 'Writing R Extensions' manual.
✔  checking for hidden files and directories ... 
W  checking for portable file names ... 
   Found the following files with non-portable file names:
     Lib/site-packages/setuptools/command/launcher manifest.xml
     Lib/site-packages/setuptools/script (dev).tmpl
   These are not fully portable file names.
   See section 'Package structure' in the 'Writing R Extensions' manual.
   Found the following non-portable file paths:
     teal.modules.clinical/Lib/site-packages/setuptools/config/_validate_pyproject/fastjsonschema_exceptions.py
     teal.modules.clinical/Lib/site-packages/setuptools/config/_validate_pyproject/fastjsonschema_validations.py
   
   Tarballs are only required to store paths of up to 100 bytes and cannot
   store those of more than 256 bytes, with restrictions including to 100
   bytes for the final component.
   See section 'Package structure' in the 'Writing R Extensions' manual.
✔  checking whether package 'teal.modules.clinical' can be installed (12s)
✔  checking installed package size (1.2s)
✔  checking package directory
✔  checking 'build' directory
✔  checking DESCRIPTION meta-information ... 
✔  checking top-level files
✔  checking for left-over files ... 
✔  checking index information ... 
✔  checking package subdirectories (1.6s)
✔  checking code files for non-ASCII characters ... 
✔  checking R files for syntax errors ... 
✔  checking whether the package can be loaded (1.5s)
✔  checking whether the package can be loaded with stated dependencies (1.5s)
✔  checking whether the package can be unloaded cleanly (1.8s)
✔  checking whether the namespace can be loaded with stated dependencies (1.6s)
✔  checking whether the namespace can be unloaded cleanly (1.9s)
✔  checking loading without being on the library search path (2.3s)
✔  checking whether startup messages can be suppressed (3.7s)
✔  checking dependencies in R code (2.9s)
✔  checking S3 generic/method consistency (1.7s)
✔  checking replacement functions (1.6s)
✔  checking foreign function calls (2.3s)
✔  checking R code for possible problems (11.9s)
✔  checking Rd files (1.8s)
✔  checking Rd metadata ... 
✔  checking Rd cross-references (459ms)
✔  checking for missing documentation entries (2s)
✔  checking for code/documentation mismatches (6.4s)
✔  checking Rd \usage sections (2.8s)
✔  checking Rd contents (726ms)
✔  checking for unstated dependencies in examples (1.8s)
✔  checking contents of 'data' directory ... 
✔  checking data for non-ASCII characters ... 
✔  checking LazyData
✔  checking data for ASCII and uncompressed saves ... 
✔  checking installed files from 'inst/doc' (456ms)
✔  checking files in 'vignettes' ... 
✔  checking examples (9.4s)
✔  checking for unstated dependencies in 'tests' ... 
─  checking tests ...
✔  Running 'testthat.R' (24.2s)
✔  checking for unstated dependencies in vignettes (514ms)
✔  checking package vignettes ... 
✔  checking re-building of vignette outputs (12.2s)
✔  checking PDF version of manual (2m 8.8s)
   
   See
     'C:/Users/kosinsm4/AppData/Local/Temp/Rtmp84khcL/file97c14113ad9/teal.modules.clinical.Rcheck/00check.log'
   for details.
   ```

**Comment by m7pr** [comment]
`min_isolated` failed - unsure if this is what suppose to happen

```r
verdepcheck::min_isolated_deps_check(".")
ℹ Creating temporary DESCRIPTION file: C:\Users\kosinsm4\AppData\Local\Temp\Rtmp84khcL\file97c4f183ab0
ℹ Creating library directory: C:\Users\kosinsm4\AppData\Local\Temp\Rtmp84khcL\file97c612e3a38
✔ Loading metadata database ... done
ℹ Getting 150 pkgs (143.06 MB), 37 (65.60 MB) cached                
✔ Cached copy of zip 2.3.1 (i386+x86_64-w64-mingw32) is the latest build                                               
✔ Cached copy of yaml 2.3.8 (i386+x86_64-w64-mingw32) is the latest build                                              
✔ Cached copy of xtable 1.8-4 (i386+x86_64-w64-mingw32) is the latest build                                            
✔ Cached copy of xml2 1.3.6 (i386+x86_64-w64-mingw32) is the latest build                                              
✔ Cached copy of withr 3.0.0 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of websocket 1.4.1 (i386+x86_64-w64-mingw32) is the latest build                                         
✔ Cached copy of waldo 0.5.2 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of vroom 1.6.5 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of viridisLite 0.4.2 (i386+x86_64-w64-mingw32) is the latest build                                       
✔ Cached copy of vctrs 0.6.5 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of uuid 1.2-0 (i386+x86_64-w64-mingw32) is the latest build                                              
✔ Cached copy of utf8 1.2.4 (i386+x86_64-w64-mingw32) is the latest build                                              
✔ Cached copy of urltools 1.7.3 (i386+x86_64-w64-mingw32) is the latest build                                          
✔ Cached copy of tzdb 0.4.0 (i386+x86_64-w64-mingw32) is the latest build                                              
✔ Cached copy of triebeard 0.4.1 (i386+x86_64-w64-mingw32) is the latest build                                         
✔ Cached copy of tidyselect 1.2.1 (i386+x86_64-w64-mingw32) is the latest build                                        
✔ Cached copy of tidyr 1.3.1 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of tibble 3.2.1 (i386+x86_64-w64-mingw32) is the latest build                                            
✔ Cached copy of textshaping 0.3.7 (i386+x86_64-w64-mingw32) is the latest build                                       
✔ Cached copy of tern.mmrm 0.3.0 (i386+x86_64-w64-mingw32) is the latest build                                         
✔ Cached copy of tern.gee 0.1.3 (i386+x86_64-w64-mingw32) is the latest build                                          
✔ Cached copy of teal.widgets 0.4.2 (i386+x86_64-w64-mingw32) is the latest build                                      
✔ Cached copy of teal.transform 0.5.0 (i386+x86_64-w64-mingw32) is the latest build                                    
✔ Cached copy of teal.slice 0.5.0 (i386+x86_64-w64-mingw32) is the latest build                                        
✔ Cached copy of teal.logger 0.2.0 (i386+x86_64-w64-mingw32) is the latest build                                       
✔ Cached copy of teal.data 0.5.0 (i386+x86_64-w64-mingw32) is the latest build                                         
✔ Cached copy of teal.code 0.5.0 (i386+x86_64-w64-mingw32) is the latest build                                         
✔ Cached copy of teal 0.15.2 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of systemfonts 1.0.6 (i386+x86_64-w64-mingw32) is the latest build                                       
✔ Cached copy of sys 3.4.2 (i386+x86_64-w64-mingw32) is the latest build                                               
✔ Cached copy of stringr 1.5.1 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of stringi 1.8.3 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of SparseM 1.81 (i386+x86_64-w64-mingw32) is the latest build                                            
✔ Cached copy of sourcetools 0.1.7-1 (i386+x86_64-w64-mingw32) is the latest build                                     
✔ Cached copy of shinyvalidate 0.1.3 (i386+x86_64-w64-mingw32) is the latest build                                     
✔ Cached copy of shinyjs 2.1.0 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of shinycssloaders 1.0.0 (i386+x86_64-w64-mingw32) is the latest build                                   
✔ Cached copy of scales 1.3.0 (i386+x86_64-w64-mingw32) is the latest build                                            
✔ Cached copy of sass 0.4.9 (i386+x86_64-w64-mingw32) is the latest build                                              
✔ Cached copy of rprojroot 2.0.4 (i386+x86_64-w64-mingw32) is the latest build                                         
✔ Cached copy of rmarkdown 2.26 (i386+x86_64-w64-mingw32) is the latest build                                          
✔ Cached copy of rlang 1.1.3 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of rematch2 2.1.2 (i386+x86_64-w64-mingw32) is the latest build                                          
✔ Cached copy of Rdpack 2.6 (i386+x86_64-w64-mingw32) is the latest build                                              
✔ Cached copy of Rcpp 1.0.12 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of RColorBrewer 1.1-3 (i386+x86_64-w64-mingw32) is the latest build                                      
✔ Cached copy of rbibutils 2.2.16 (i386+x86_64-w64-mingw32) is the latest build                                        
✔ Cached copy of rappdirs 0.3.3 (i386+x86_64-w64-mingw32) is the latest build                                          
✔ Cached copy of R6 2.5.1 (i386+x86_64-w64-mingw32) is the latest build                                                
✔ Cached copy of R.utils 2.12.3 (i386+x86_64-w64-mingw32) is the latest build                                          
✔ Cached copy of R.oo 1.26.0 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of R.methodsS3 1.8.2 (i386+x86_64-w64-mingw32) is the latest build                                       
✔ Cached copy of R.cache 0.16.0 (i386+x86_64-w64-mingw32) is the latest build                                          
✔ Cached copy of quantreg 5.97 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of quadprog 1.5-8 (i386+x86_64-w64-mingw32) is the latest build                                          
✔ Cached copy of purrr 1.0.2 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of ps 1.7.6 (i386+x86_64-w64-mingw32) is the latest build                                                
✔ Cached copy of processx 3.8.4 (i386+x86_64-w64-mingw32) is the latest build                                          
✔ Cached copy of praise 1.0.0 (i386+x86_64-w64-mingw32) is the latest build                                            
✔ Cached copy of plotly 4.10.4 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of pkgload 1.3.4 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of pkgconfig 2.0.3 (i386+x86_64-w64-mingw32) is the latest build                                         
✔ Cached copy of pkgbuild 1.4.4 (i386+x86_64-w64-mingw32) is the latest build                                          
✔ Cached copy of pillar 1.9.0 (i386+x86_64-w64-mingw32) is the latest build                                            
✔ Cached copy of pbkrtest 0.5.2 (i386+x86_64-w64-mingw32) is the latest build                                          
✔ Cached copy of openssl 2.1.1 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of officer 0.6.5 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of numDeriv 2016.8-1.1 (i386+x86_64-w64-mingw32) is the latest build                                     
✔ Cached copy of nloptr 2.0.3 (i386+x86_64-w64-mingw32) is the latest build                                            
✔ Cached copy of nestcolor 0.1.2 (i386+x86_64-w64-mingw32) is the latest build                                         
✔ Cached copy of mvtnorm 1.2-4 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of munsell 0.5.1 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of mosaicCore 0.9.4.0 (i386+x86_64-w64-mingw32) is the latest build                                      
✔ Cached copy of minqa 1.2.6 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of mime 0.12 (i386+x86_64-w64-mingw32) is the latest build                                               
✔ Cached copy of MESS 0.5.12 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of memoise 2.0.1 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of MatrixModels 0.5-3 (i386+x86_64-w64-mingw32) is the latest build                                      
✔ Cached copy of magrittr 2.0.3 (i386+x86_64-w64-mingw32) is the latest build                                          
✔ Cached copy of logger 0.3.0 (i386+x86_64-w64-mingw32) is the latest build                                            
✔ Cached copy of lifecycle 1.0.4 (i386+x86_64-w64-mingw32) is the latest build                                         
✔ Cached copy of lazyeval 0.2.2 (i386+x86_64-w64-mingw32) is the latest build                                          
✔ Cached copy of later 1.3.2 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of labelled 2.12.0 (i386+x86_64-w64-mingw32) is the latest build                                         
✔ Cached copy of labeling 0.4.3 (i386+x86_64-w64-mingw32) is the latest build                                          
✔ Cached copy of jsonlite 1.8.8 (i386+x86_64-w64-mingw32) is the latest build                                          
✔ Cached copy of jquerylib 0.1.4 (i386+x86_64-w64-mingw32) is the latest build                                         
✔ Cached copy of iterators 1.0.14 (i386+x86_64-w64-mingw32) is the latest build                                        
✔ Cached copy of isoband 0.2.7 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of httr 1.4.7 (i386+x86_64-w64-mingw32) is the latest build                                              
✔ Cached copy of httpcode 0.3.0 (i386+x86_64-w64-mingw32) is the latest build                                          
✔ Cached copy of htmlwidgets 1.6.4 (i386+x86_64-w64-mingw32) is the latest build                                       
✔ Cached copy of htmltools 0.5.8.1 (i386+x86_64-w64-mingw32) is the latest build                                       
✔ Cached copy of hms 1.1.3 (i386+x86_64-w64-mingw32) is the latest build                                               
✔ Cached copy of highr 0.10 (i386+x86_64-w64-mingw32) is the latest build                                              
✔ Cached copy of haven 2.5.4 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of gtable 0.3.4 (i386+x86_64-w64-mingw32) is the latest build                                            
✔ Cached copy of gridExtra 2.3 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of glue 1.7.0 (i386+x86_64-w64-mingw32) is the latest build                                              
✔ Cached copy of glmnet 4.1-8 (i386+x86_64-w64-mingw32) is the latest build                                            
✔ Cached copy of ggplot2 3.5.0 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of ggformula 0.12.0 (i386+x86_64-w64-mingw32) is the latest build                                        
✔ Cached copy of gfonts 0.2.0 (i386+x86_64-w64-mingw32) is the latest build                                            
✔ Cached copy of generics 0.1.3 (i386+x86_64-w64-mingw32) is the latest build                                          
✔ Cached copy of geeM 0.10.1 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of geeasy 0.1.1 (i386+x86_64-w64-mingw32) is the latest build                                            
✔ Cached copy of gdtools 0.3.7 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of fs 1.6.3 (i386+x86_64-w64-mingw32) is the latest build                                                
✔ Cached copy of foreach 1.5.2 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of forcats 1.0.0 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of fontquiver 0.2.1 (i386+x86_64-w64-mingw32) is the latest build                                        
✔ Cached copy of fontLiberation 0.1.0 (i386+x86_64-w64-mingw32) is the latest build                                    
✔ Cached copy of fontBitstreamVera 0.1.1 (i386+x86_64-w64-mingw32) is the latest build                                 
✔ Cached copy of fontawesome 0.5.2 (i386+x86_64-w64-mingw32) is the latest build                                       
✔ Cached copy of flextable 0.9.5 (i386+x86_64-w64-mingw32) is the latest build                                         
✔ Cached copy of fastmap 1.1.1 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of farver 2.1.1 (i386+x86_64-w64-mingw32) is the latest build                                            
✔ Cached copy of fansi 1.0.6 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of evaluate 0.23 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of estimability 1.5 (i386+x86_64-w64-mingw32) is the latest build                                        
✔ Cached copy of emmeans 1.10.1 (i386+x86_64-w64-mingw32) is the latest build                                          
✔ Cached copy of ellipsis 0.3.2 (i386+x86_64-w64-mingw32) is the latest build                                          
✔ Cached copy of dplyr 1.1.4 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of digest 0.6.35 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of diffobj 0.3.5 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of desc 1.4.3 (i386+x86_64-w64-mingw32) is the latest build                                              
✔ Cached copy of curl 5.2.1 (i386+x86_64-w64-mingw32) is the latest build                                              
✔ Cached copy of crul 1.4.0 (i386+x86_64-w64-mingw32) is the latest build                                              
✔ Cached copy of crosstalk 1.2.1 (i386+x86_64-w64-mingw32) is the latest build                                         
✔ Cached copy of crayon 1.5.2 (i386+x86_64-w64-mingw32) is the latest build                                            
✔ Cached copy of cowplot 1.1.3 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of commonmark 1.9.1 (i386+x86_64-w64-mingw32) is the latest build                                        
✔ Cached copy of colorspace 2.1-0 (i386+x86_64-w64-mingw32) is the latest build                                        
✔ Cached copy of clipr 0.8.0 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of cli 3.6.2 (i386+x86_64-w64-mingw32) is the latest build                                               
✔ Cached copy of checkmate 2.3.1 (i386+x86_64-w64-mingw32) is the latest build                                         
✔ Cached copy of carData 3.0-5 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of car 3.1-2 (i386+x86_64-w64-mingw32) is the latest build                                               
✔ Cached copy of callr 3.7.6 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of cachem 1.0.8 (i386+x86_64-w64-mingw32) is the latest build                                            
✔ Cached copy of broom 1.0.5 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of brio 1.1.4 (i386+x86_64-w64-mingw32) is the latest build                                              
✔ Cached copy of bit64 4.0.5 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ Cached copy of bit 4.0.5 (i386+x86_64-w64-mingw32) is the latest build                                               
✔ Cached copy of base64enc 0.1-3 (i386+x86_64-w64-mingw32) is the latest build                                         
✔ Cached copy of backports 1.4.1 (i386+x86_64-w64-mingw32) is the latest build                                         
✔ Cached copy of assertive.base 0.0-9 (i386+x86_64-w64-mingw32) is the latest build                                    
✔ Cached copy of askpass 1.2.0 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of anytime 0.3.9 (i386+x86_64-w64-mingw32) is the latest build                                           
✔ Cached copy of abind 1.4-5 (i386+x86_64-w64-mingw32) is the latest build                                             
✔ No downloads needed, all packages are cached                                                                          
✔ Installed zip 2.3.1  (631ms)                                                                                       
✔ Installed yaml 2.3.8  (783ms)                        
✔ Installed xtable 1.8-4  (935ms)                      
✔ Installed xml2 1.3.6  (1.1s)                         
✔ Installed xfun 0.42  (1.2s)                         
✔ Installed withr 3.0.0  (1.4s)                       
✔ Installed websocket 1.4.1  (1.6s)                                                                                      
✔ Installed waldo 0.5.2  (1.7s)                                                                                        
✔ Installed viridisLite 0.4.2  (1.9s)                                                                           
✔ Installed vroom 1.6.5  (2.3s)                                                                      
✔ Installed uuid 1.2-0  (2.6s)                                                                    
✔ Installed vctrs 0.6.5  (2.9s)                                                                        
✔ Installed utf8 1.2.4  (1.2s)                                                                                
✔ Installed urltools 1.7.3  (1.3s)                                                                                
✔ Installed tzdb 0.4.0  (1.6s)                                                                                           
✔ Installed triebeard 0.4.1  (1.8s)                                                                                    
✔ Installed tinytex 0.49  (1.9s)                      
✔ Installed TMB 1.9.10  (2.3s)                        
✔ Installed tidyselect 1.2.1  (2.3s)                  
✔ Installed tidyr 1.3.1  (2.7s)                        
✔ Installed tibble 3.2.1  (2.8s)                       
✔ Installed textshaping 0.3.7  (2.7s)                  
✔ Installed testthat 3.2.1.1  (3.1s)                   
✔ Installed tern.mmrm 0.3.0  (3.2s)                    
✔ Installed tern.gee 0.1.3  (3.5s)                     
✔ Installed tern 0.9.4  (3.5s)                         
✔ Installed teal.widgets 0.4.2  (3.7s)                 
✔ Installed teal.transform 0.5.0  (3.7s)               
✔ Installed teal.slice 0.5.0  (4s)                     
✔ Installed teal.reporter 0.3.0  (4s)                  
✔ Installed teal.logger 0.2.0  (4s)                    
✔ Installed teal.data 0.5.0  (4.4s)                    
✔ Installed teal.code 0.5.0  (4.3s)                    
✔ Installed teal 0.15.2  (4.5s)                        
✔ Installed systemfonts 1.0.6  (4.4s)                  
✔ Installed sys 3.4.2  (4.5s)                          
✔ Installed styler 1.10.2  (4.4s)                      
✔ Installed stringr 1.5.1  (4.8s)                      
✔ Installed stringi 1.8.3  (4.8s)                      
✔ Installed SparseM 1.81  (4.8s)                       
✔ Installed sourcetools 0.1.7-1  (4.8s)                
✔ Installed shinyvalidate 0.1.3  (4.4s)                
✔ Installed shinyWidgets 0.8.2  (5.3s)                 
✔ Installed shinyjs 2.1.0  (4.6s)                      
✔ Installed shinycssloaders 1.0.0  (4.7s)              
✔ Installed shiny 1.8.0  (4.7s)                        
✔ Installed shape 1.4.6  (4.7s)                        
✔ Installed RColorBrewer 1.1-3  (156ms)                
✔ Installed scales 1.3.0  (5s)                         
✔ Installed sass 0.4.9  (5s)                           
✔ Installed rtables 0.6.7  (5s)                        
✔ Installed rprojroot 2.0.4  (5s)                      
✔ Installed rmarkdown 2.26  (5.1s)                     
✔ Installed rlistings 0.2.8  (5s)                      
✔ Installed rlang 1.1.3  (5.2s)                        
✔ Installed R.methodsS3 1.8.2  (548ms)                 
✔ Installed rematch2 2.1.2  (5.5s)                     
✔ Installed readr 2.1.4  (5.4s)                        
✔ Installed Rdpack 2.6  (5.5s)                         
✔ Installed Rcpp 1.0.12  (5.6s)                        
✔ Installed rbibutils 2.2.16  (5.2s)                   
✔ Installed rappdirs 0.3.3  (5.2s)                     
✔ Installed ragg 1.2.7  (5.4s)                         
✔ Installed R6 2.5.1  (5.2s)                           
✔ Installed R.utils 2.12.3  (5.3s)                     
✔ Installed R.oo 1.26.0  (5.3s)                        
✔ Installed R.cache 0.16.0  (4.4s)                     
✔ Installed quantreg 5.97  (4.8s)                      
✔ Installed quadprog 1.5-8  (4.7s)                     
✔ Installed purrr 1.0.2  (4.8s)                        
✔ Installed ps 1.7.6  (4.7s)                           
✔ Installed promises 1.2.1  (4.6s)                     
✔ Installed processx 3.8.4  (4.7s)                     
✔ Installed praise 1.0.0  (4.7s)                       
✔ Installed plotly 4.10.4  (4.5s)                      
✔ Installed pkgload 1.3.4  (4.5s)                      
✔ Installed pkgconfig 2.0.3  (4.5s)                    
✔ Installed pkgbuild 1.4.4  (4.5s)                     
✔ Installed pingr 2.0.1  (4.5s)                        
✔ Installed pillar 1.9.0  (4.5s)                       
✔ Installed pbkrtest 0.5.2  (4.6s)                     
✔ Installed minqa 1.2.6  (621ms)                       
✔ Installed parallelly 1.36.0  (4.9s)                  
✔ Installed openssl 2.1.1  (5s)                        
✔ Installed officer 0.6.5  (5s)                        
✔ Installed MatrixModels 0.5-3  (442ms)                
✔ Installed numDeriv 2016.8-1.1  (5.1s)                
✔ Installed nloptr 2.0.3  (5.4s)                       
✔ Installed nestcolor 0.1.2  (5.4s)                    
✔ Installed mvtnorm 1.2-4  (5.4s)                      
✔ Installed munsell 0.5.1  (5.5s)                       
✔ Installed mosaicCore 0.9.4.0  (5.5s)                  
✔ Installed mmrm 0.3.7  (5.5s)                          
✔ Installed mime 0.12  (4.7s)                           
✔ Installed MESS 0.5.12  (4.7s)                         
✔ Installed memoise 2.0.1  (4.9s)                       
✔ Installed magrittr 2.0.3  (4.4s)                      
✔ Installed logger 0.3.0  (4.4s)                        
✔ Installed lme4 1.1-35.3  (4.8s)                       
✔ Installed lifecycle 1.0.4  (4.6s)                     
✔ Installed lazyeval 0.2.2  (4.7s)                      
✔ Installed later 1.3.2  (4.7s)                         
✔ Installed labelled 2.12.0  (4.5s)                     
✔ Installed labeling 0.4.3  (4.4s)                      
✔ Installed knitr 1.45  (4.4s)                          
✔ Installed kinship2 1.9.6  (4.4s)                      
✔ Installed jsonlite 1.8.8  (4.3s)                      
✔ Installed jquerylib 0.1.4  (4.4s)                     
✔ Installed iterators 1.0.14  (4.4s)                    
✔ Installed isoband 0.2.7  (4.4s)                       
✔ Installed httr 1.4.7  (4.5s)                          
✔ Installed httpuv 1.6.14  (4.5s)                       
✔ Installed httpcode 0.3.0  (4.6s)                      
✔ Installed htmlwidgets 1.6.4  (4.5s)                   
✔ Installed htmltools 0.5.8.1  (4.6s)                   
✔ Installed hms 1.1.3  (4.6s)                           
✔ Installed highr 0.10  (4.8s)                          
✔ Installed geepack 1.3.9  (615ms)                      
✔ Installed haven 2.5.4  (5.1s)                         
✔ Installed gtable 0.3.4  (5.1s)                        
✔ Installed gridExtra 2.3  (5.1s)                       
✔ Installed glue 1.7.0  (5.1s)                          
✔ Installed glmnet 4.1-8  (5s)                          
✔ Installed ggridges 0.5.4  (4.9s)                      
✔ Installed ggplot2 3.5.0  (4.9s)                       
✔ Installed ggformula 0.12.0  (4.9s)                    
✔ Installed gfonts 0.2.0  (5s)                          
✔ Installed generics 0.1.3  (5.1s)                      
ℹ Building lubridate 1.7.9                              
✔ Installed geeM 0.10.1  (6.3s)                         
✔ Installed geeasy 0.1.1  (6.6s)                        
✔ Installed gdtools 0.3.7  (6.5s)                       
✔ Installed fs 1.6.3  (6.3s)                           
✔ Installed formatters 0.5.6  (6.1s)                   
✔ Installed foreach 1.5.2  (6.1s)                      
✔ Installed forcats 1.0.0  (6s)                        
✔ Installed fontquiver 0.2.1  (6.2s)                   
✔ Installed fontLiberation 0.1.0  (6.1s)               
✔ Installed fontBitstreamVera 0.1.1  (6.1s)            
✔ Installed fontawesome 0.5.2  (6.1s)                                                                               
✖ Failed to build lubridate 1.7.9 (3.9s)                                                                          
! Failed to build source package lubridate., stdout + stderr:                                  

OE> Error in rawToChar(block[seq_len(ns)]) : 
OE>   embedded nul in string: 'PK\003\004\n\0\0\0\0\0Nj\xc5X\0\0\0\0\0\0\0\0\0\0\0\0\n\0\0\0lubridate/PK\003\004\024\0\002\0\b\0Hj\xc5Xf\x97\x96J\xc9\0\0\0s\001\0\0\021\0\0\0lubridate/cctz.shM\x90\xbdn\xc30\f\x84w>\005\x9bz'
Error in "stop_task_build(state, worker)" : 
  ! Failed to build source package lubridate.
```

**Comment by m7pr** [comment]
`release_deps` was proper

```r
verdepcheck::release_deps_check(".")
ℹ Creating temporary DESCRIPTION file: C:\Users\kosinsm4\AppData\Local\Temp\Rtmp84khcL\file97c67e211a4
ℹ Creating library directory: C:\Users\kosinsm4\AppData\Local\Temp\Rtmp84khcL\file97c9fc3b2b
ℹ Getting 147 pkgs (132.02 MB), 40 (78.20 MB) cached                        
✔ Cached copy of abind 1.4-5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of anytime 0.3.9 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of askpass 1.2.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of assertthat 0.2.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of base64enc 0.1-3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of bit 4.0.5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of bit64 4.0.5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of bslib 0.7.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of callr 3.7.6 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of checkmate 2.3.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of chromote 0.2.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of cli 3.6.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of clipr 0.8.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of colorspace 2.1-0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of commonmark 1.9.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of curl 5.2.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of data.table 1.15.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of desc 1.4.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of diffobj 0.3.5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of digest 0.6.35 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of dplyr 1.1.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of DT 0.33 (i386+x86_64-w64-mingw32) is the latest build  
✔ Cached copy of evaluate 0.23 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of fansi 1.0.6 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of fontawesome 0.5.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of fontBitstreamVera 0.1.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of fontLiberation 0.1.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of fontquiver 0.2.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of forcats 1.0.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of foreach 1.5.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of geeM 0.10.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of geepack 1.3.10 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of generics 0.1.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of gfonts 0.2.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of ggrepel 0.9.5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of ggridges 0.5.6 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of glmnet 4.1-8 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of globals 0.16.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of glue 1.7.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of gridExtra 2.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of haven 2.5.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of hms 1.1.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of httpcode 0.3.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of httpuv 1.6.15 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of httr 1.4.7 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of isoband 0.2.7 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of iterators 1.0.14 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of jquerylib 0.1.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of jsonlite 1.8.8 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of kinship2 1.9.6.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of labeling 0.4.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of later 1.3.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of lazyeval 0.2.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of lifecycle 1.0.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of magrittr 2.0.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of MatrixModels 0.5-3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of memoise 2.0.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of MESS 0.5.12 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of mime 0.12 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of mmrm 0.3.11 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of mosaicCore 0.9.4.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of munsell 0.5.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of nestcolor 0.1.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of nloptr 2.0.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of numDeriv 2016.8-1.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of parallelly 1.37.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of pbkrtest 0.5.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of pillar 1.9.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of pkgbuild 1.4.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of pkgconfig 2.0.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of pkgload 1.3.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of plotly 4.10.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of praise 1.0.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of promises 1.3.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of ps 1.7.6 (i386+x86_64-w64-mingw32) is the latest build 
✔ Cached copy of purrr 1.0.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of quadprog 1.5-8 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of R.cache 0.16.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of R.methodsS3 1.8.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of R.oo 1.26.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of R.utils 2.12.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of R6 2.5.1 (i386+x86_64-w64-mingw32) is the latest build 
✔ Cached copy of rbibutils 2.2.16 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of RColorBrewer 1.1-3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of Rcpp 1.0.12 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of Rdpack 2.6 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of readr 2.1.5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of rematch2 2.1.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of rlang 1.1.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of rprojroot 2.0.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of rvest 1.0.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of sass 0.4.9 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of scales 1.3.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of selectr 0.4-2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of shape 1.4.6.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of shiny 1.8.1.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of shinyvalidate 0.1.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of sourcetools 0.1.7-1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of stringr 1.5.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of styler 1.10.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of sys 3.4.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of teal 0.15.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of teal.code 0.5.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of teal.logger 0.2.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of teal.reporter 0.3.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of teal.transform 0.5.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of teal.widgets 0.4.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of tern.gee 0.1.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of tibble 3.2.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of tidyr 1.3.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of tidyselect 1.2.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of timechange 0.3.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of TMB 1.9.11 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of triebeard 0.4.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of tzdb 0.4.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of urltools 1.7.3 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of utf8 1.2.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of uuid 1.2-0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of vctrs 0.6.5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of viridisLite 0.4.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of vistime 1.2.4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of vroom 1.6.5 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of waldo 0.5.2 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of withr 3.0.0 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of xml2 1.3.6 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of xtable 1.8-4 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of yaml 2.3.8 (i386+x86_64-w64-mingw32) is the latest build
✔ Cached copy of zip 2.3.1 (i386+x86_64-w64-mingw32) is the latest build
✔ Got car 3.1-2 (i386+x86_64-w64-mingw32) (1.73 MB)                                                                     
✔ Got carData 3.0-5 (i386+x86_64-w64-mingw32) (1.71 MB)                              
✔ Got cowplot 1.1.3 (i386+x86_64-w64-mingw32) (1.38 MB)                              
✔ Got htmltools 0.5.8.1 (i386+x86_64-w64-mingw32) (364.88 kB)                        
✔ Got htmlwidgets 1.6.4 (i386+x86_64-w64-mingw32) (814.05 kB)                        
✔ Got shinybusy 0.3.3 (i386+x86_64-w64-mingw32) (624.45 kB)                          
✔ Got shinycssloaders 1.0.0 (i386+x86_64-w64-mingw32) (141.29 kB)                    
✔ Got shinyjs 2.1.0 (i386+x86_64-w64-mingw32) (1.11 MB)                              
✔ Got gdtools 0.3.7 (i386+x86_64-w64-mingw32) (2.19 MB)                              
✔ Got ggformula 0.12.0 (i386+x86_64-w64-mingw32) (1.83 MB)                           
✔ Got tern.mmrm 0.3.0 (i386+x86_64-w64-mingw32) (568.88 kB)                          
✔ Got ggplot2 3.5.1 (i386+x86_64-w64-mingw32) (5.02 MB)                              
✔ Got processx 3.8.4 (i386+x86_64-w64-mingw32) (685.53 kB)                           
✔ Got rappdirs 0.3.3 (i386+x86_64-w64-mingw32) (52.48 kB)                            
✔ Got pingr 2.0.3 (i386+x86_64-w64-mingw32) (60.49 kB)                               
✔ Got crayon 1.5.2 (i386+x86_64-w64-mingw32) (165.39 kB)                             
✔ Got crosstalk 1.2.1 (i386+x86_64-w64-mingw32) (416.80 kB)                          
✔ Got flextable 0.9.6 (i386+x86_64-w64-mingw32) (3.24 MB)                            
✔ Got lubridate 1.9.3 (i386+x86_64-w64-mingw32) (989.98 kB)                          
✔ Got logger 0.3.0 (i386+x86_64-w64-mingw32) (757.59 kB)                             
✔ Got websocket 1.4.1 (i386+x86_64-w64-mingw32) (2.80 MB)                            
✔ Got lme4 1.1-35.3 (i386+x86_64-w64-mingw32) (4.55 MB)                              
✔ Got stringi 1.8.4 (i386+x86_64-w64-mingw32) (15.01 MB)                             
✔ Downloaded 23 packages (46.21 MB) in 56.7s                                         
✔ Installed abind 1.4-5  (627ms)                                                                             
✔ Installed anytime 0.3.9  (783ms)                     
✔ Installed askpass 1.2.0  (1s)                        
✔ Installed assertthat 0.2.1  (1.2s)                   
✔ Installed backports 1.5.0  (1.3s)                   
✔ Installed base64enc 0.1-3  (1.5s)                   
✔ Installed bit 4.0.5  (1.7s)                                                                                     
✔ Installed bit64 4.0.5  (2s)                                                                                   
✔ Installed brio 1.1.5  (2.2s)                                                                       
✔ Installed broom 1.0.6  (2.4s)                                                                 
✔ Installed cachem 1.1.0  (2.7s)                                                         
✔ Installed bslib 0.7.0  (3.1s)                                                    
✔ Installed callr 3.7.6  (697ms)                                                    
✔ Installed car 3.1-2  (722ms)                                                          
✔ Installed carData 3.0-5  (733ms)                                                           
✔ Installed checkmate 2.3.1  (818ms)                                                       
✔ Installed chromote 0.2.0  (930ms)                                                    
✔ Installed cli 3.6.2  (1.1s)                                                                      
✔ Installed clipr 0.8.0  (1.4s)                                                                                
✔ Installed commonmark 1.9.1  (1.5s)                                                                                     
✔ Installed colorspace 2.1-0  (2s)                                                                                     
✔ Installed cowplot 1.1.3  (2.1s)                                                                                        
✔ Installed crayon 1.5.2  (2.4s)                                                                                         
✔ Installed crosstalk 1.2.1  (2.3s)                                                                                    
✔ Installed crul 1.4.2  (2.7s)                                                                                         
✔ Installed curl 5.2.1  (2.7s)                        
✔ Installed desc 1.4.3  (2.8s)                         
✔ Installed data.table 1.15.4  (3.4s)                  
✔ Installed fastmap 1.2.0  (556ms)                     
✔ Installed diffobj 0.3.5  (3.7s)                      
✔ Installed digest 0.6.35  (3.7s)                      
✔ Installed dplyr 1.1.4  (4s)                          
✔ Installed emmeans 1.10.2  (3.9s)                     
✔ Installed estimability 1.5.1  (3.9s)                 
✔ Installed DT 0.33  (4.9s)                            
✔ Installed evaluate 0.23  (4.2s)                      
✔ Installed fansi 1.0.6  (4.3s)                        
✔ Installed farver 2.1.2  (4.3s)                       
✔ Installed flextable 0.9.6  (4.1s)                    
✔ Installed fontawesome 0.5.2  (4.5s)                  
✔ Installed fontBitstreamVera 0.1.1  (4.3s)            
✔ Installed fontLiberation 0.1.0  (4.3s)               
✔ Installed fontquiver 0.2.1  (4.4s)                   
✔ Installed forcats 1.0.0  (4.4s)                      
✔ Installed foreach 1.5.2  (4.7s)                      
✔ Installed formatters 0.5.6  (4.9s)                   
✔ Installed fs 1.6.4  (4.9s)                           
✔ Installed globals 0.16.3  (365ms)                    
✔ Installed gdtools 0.3.7  (5.5s)                      
✔ Installed geeasy 0.1.2  (5.6s)                       
✔ Installed geeM 0.10.1  (5.7s)                        
✔ Installed geepack 1.3.10  (5.5s)                     
✔ Installed generics 0.1.3  (5.4s)                     
✔ Installed gfonts 0.2.0  (5.6s)                       
✔ Installed ggformula 0.12.0  (5.5s)                   
✔ Installed ggplot2 3.5.1  (5.4s)                      
✔ Installed ggrepel 0.9.5  (5.3s)                      
✔ Installed ggridges 0.5.6  (5.1s)                     
✔ Installed glmnet 4.1-8  (5.1s)                       
✔ Installed glue 1.7.0  (4.5s)                         
✔ Installed gridExtra 2.3  (4.4s)                      
✔ Installed gtable 0.3.5  (4.5s)                       
✔ Installed haven 2.5.4  (4.5s)                        
✔ Installed highr 0.11  (4.6s)                         
✔ Installed hms 1.1.3  (4.6s)                          
✔ Installed htmltools 0.5.8.1  (4.5s)                  
✔ Installed htmlwidgets 1.6.4  (4.6s)                  
✔ Installed httpcode 0.3.0  (4.7s)                     
✔ Installed httpuv 1.6.15  (4.6s)                      
✔ Installed httr 1.4.7  (4.7s)                         
✔ Installed isoband 0.2.7  (4.8s)                      
✔ Installed iterators 1.0.14  (4.8s)                   
✔ Installed jquerylib 0.1.4  (4.7s)                    
✔ Installed jsonlite 1.8.8  (4.8s)                     
✔ Installed kinship2 1.9.6.1  (4.7s)                   
✔ Installed knitr 1.47  (4.7s)                         
✔ Installed labeling 0.4.3  (4.6s)                     
✔ Installed labelled 2.13.0  (4.6s)                    
✔ Installed later 1.3.2  (4.7s)                        
✔ Installed lazyeval 0.2.2  (4.6s)                     
✔ Installed mosaicCore 0.9.4.0  (160ms)                
✔ Installed lifecycle 1.0.4  (5s)                      
✔ Installed lme4 1.1-35.3  (4.9s)                      
✔ Installed logger 0.3.0  (5s)                         
✔ Installed lubridate 1.9.3  (5s)                      
✔ Installed magrittr 2.0.3  (5.1s)                     
✔ Installed MatrixModels 0.5-3  (5s)                   
✔ Installed memoise 2.0.1  (5s)                        
✔ Installed MESS 0.5.12  (4.9s)                        
✔ Installed mime 0.12  (4.9s)                          
✔ Installed minqa 1.2.7  (4.8s)                         
✔ Installed mmrm 0.3.11  (4.8s)                         
✔ Installed munsell 0.5.1  (4.7s)                       
✔ Installed mvtnorm 1.2-5  (4.6s)                       
✔ Installed nestcolor 0.1.2  (4.6s)                     
✔ Installed nloptr 2.0.3  (4.6s)                        
✔ Installed numDeriv 2016.8-1.1  (4.6s)                 
✔ Installed officer 0.6.6  (4.6s)                       
✔ Installed openssl 2.2.0  (4.6s)                       
✔ Installed parallelly 1.37.1  (4.6s)                   
✔ Installed pbkrtest 0.5.2  (4.7s)                      
✔ Installed pillar 1.9.0  (4.7s)                        
✔ Installed pingr 2.0.3  (4.8s)                         
✔ Installed pkgbuild 1.4.4  (4.8s)                      
✔ Installed pkgconfig 2.0.3  (4.6s)                     
✔ Installed pkgload 1.3.4  (4.6s)                       
✔ Installed plotly 4.10.4  (4.7s)                       
✔ Installed praise 1.0.0  (4.5s)                        
✔ Installed processx 3.8.4  (4.5s)                      
✔ Installed promises 1.3.0  (4.6s)                      
✔ Installed ps 1.7.6  (4.6s)                            
✔ Installed purrr 1.0.2  (4.7s)                         
✔ Installed quadprog 1.5-8  (4.8s)                      
✔ Installed quantreg 5.98  (4.8s)                       
✔ Installed R.cache 0.16.0  (4.8s)                      
✔ Installed R.methodsS3 1.8.2  (4.8s)                   
✔ Installed R.oo 1.26.0  (4.8s)                         
✔ Installed R.utils 2.12.3  (4.8s)                      
✔ Installed R6 2.5.1  (4.8s)                            
✔ Installed ragg 1.3.2  (4.9s)                          
✔ Installed rappdirs 0.3.3  (4.8s)                      
✔ Installed rbibutils 2.2.16  (4.8s)                    
✔ Installed RColorBrewer 1.1-3  (4.8s)                  
✔ Installed Rdpack 2.6  (4.2s)                          
✔ Installed Rcpp 1.0.12  (5.2s)                         
✔ Installed readr 2.1.5  (4.6s)                         
✔ Installed rematch2 2.1.2  (4.6s)                      
✔ Installed rlang 1.1.3  (4.7s)                         
✔ Installed rlistings 0.2.8  (4.7s)                     
✔ Installed rmarkdown 2.27  (5s)                        
✔ Installed rprojroot 2.0.4  (5s)                       
✔ Installed rtables 0.6.7  (5s)                         
✔ Installed rvest 1.0.4  (5.1s)                         
✔ Installed sass 0.4.9  (5.2s)                          
✔ Installed scales 1.3.0  (5.3s)                        
✔ Installed selectr 0.4-2  (5.2s)                       
✔ Installed shape 1.4.6.1  (5.4s)                       
✔ Installed shiny 1.8.1.1  (5.4s)                       
✔ Installed shinybusy 0.3.3  (5.3s)                     
✔ Installed shinycssloaders 1.0.0  (5.2s)               
✔ Installed shinyjs 2.1.0  (4.9s)                       
✔ Installed shinytest2 0.3.2  (4.9s)                    
✔ Installed shinyvalidate 0.1.3  (5s)                   
✔ Installed sourcetools 0.1.7-1  (4.4s)                 
✔ Installed shinyWidgets 0.8.6  (5.4s)                  
✔ Installed SparseM 1.83  (4.8s)                        
✔ Installed stringi 1.8.4  (4.9s)                       
✔ Installed stringr 1.5.1  (4.9s)                       
✔ Installed styler 1.10.3  (4.8s)                       
✔ Installed sys 3.4.2  (4.8s)                           
✔ Installed systemfonts 1.1.0  (4.9s)                   
✔ Installed teal 0.15.2  (4.8s)                         
✔ Installed teal.code 0.5.0  (4.8s)                     
✔ Installed teal.data 0.6.0  (4.9s)                     
✔ Installed teal.logger 0.2.0  (4.8s)                   
✔ Installed teal.reporter 0.3.1  (4.8s)                 
✔ Installed teal.slice 0.5.1  (4.7s)                    
✔ Installed teal.transform 0.5.0  (4.7s)                
✔ Installed teal.widgets 0.4.2  (4.5s)                  
✔ Installed tern 0.9.4  (4.5s)                          
✔ Installed tern.gee 0.1.3  (4.6s)                      
✔ Installed tern.mmrm 0.3.0  (4.6s)                     
✔ Installed testthat 3.2.1.1  (4.7s)                    
✔ Installed textshaping 0.4.0  (4.8s)                   
✔ Installed tibble 3.2.1  (5.1s)                        
✔ Installed tidyr 1.3.1  (4.9s)                         
✔ Installed tidyselect 1.2.1  (5.1s)                    
✔ Installed timechange 0.3.0  (5.2s)                    
✔ Installed tinytex 0.51  (5.3s)                        
✔ Installed triebeard 0.4.1  (5s)                       
✔ Installed TMB 1.9.11  (5.9s)                          
✔ Installed tzdb 0.4.0  (5.5s)                          
✔ Installed urltools 1.7.3  (5.5s)                      
✔ Installed utf8 1.2.4  (5.5s)                          
✔ Installed uuid 1.2-0  (5.5s)                          
✔ Installed vctrs 0.6.5  (5.3s)                         
✔ Installed viridisLite 0.4.2  (5.1s)                   
✔ Installed vistime 1.2.4  (5.1s)                       
✔ Installed vroom 1.6.5  (4.9s)                        
✔ Installed waldo 0.5.2  (4.7s)                                                                                         
✔ Installed websocket 1.4.1  (4.7s)                                                                                   
✔ Installed withr 3.0.0  (4.6s)                                                                                
✔ Installed xfun 0.44  (4.6s)                                                                       
✔ Installed xml2 1.3.6  (4.5s)                                                               
✔ Installed xtable 1.8-4  (4.3s)                                                       
✔ Installed yaml 2.3.8  (4.2s)                                                   
✔ Installed zip 2.3.1  (4s)                                              
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Rprojects\teal.modules.clinical/DESCRIPTION' ...
─  preparing 'teal.modules.clinical': (5.2s)
✔  checking DESCRIPTION meta-information ... 
─  installing the package to build vignettes (2.2s)
✔  creating vignettes (24.5s)
─  checking for LF line-endings in source and make files and shell scripts (2.2s)
─  checking for empty or unneeded directories
   Removed empty directory 'teal.modules.clinical/Include'
─  building 'teal.modules.clinical_0.9.1.9006.tar.gz'
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     'teal.modules.clinical/Lib/site-packages/setuptools/config/_validate_pyproject/fastjsonschema_exceptions.py'
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     'teal.modules.clinical/Lib/site-packages/setuptools/config/_validate_pyproject/fastjsonschema_validations.py'
   
── R CMD check ─────────────────────────────────────────────────────────────────────────────────────────────────────────
─  using log directory 'C:/Users/kosinsm4/AppData/Local/Temp/Rtmp84khcL/file97c8d73e0e/teal.modules.clinical.Rcheck' (502ms)
─  using R version 4.4.0 (2024-04-24 ucrt)
─  using platform: x86_64-w64-mingw32
─  R was compiled by
       gcc.exe (GCC) 13.2.0
       GNU Fortran (GCC) 13.2.0
─  running under: Windows 11 x64 (build 22621)
─  using session charset: UTF-8
✔  checking for file 'teal.modules.clinical/DESCRIPTION' (2.3s)
─  this is package 'teal.modules.clinical' version '0.9.1.9006'
─  package encoding: UTF-8
✔  checking package namespace information
✔  checking package dependencies (1.3s)
✔  checking if this is a source package ...
✔  checking if there is a namespace
W  checking for executable files (28.3s)
   Found the following executable files:
     Lib/site-packages/pip/_vendor/distlib/t32.exe
     Lib/site-packages/pip/_vendor/distlib/t64-arm.exe
     Lib/site-packages/pip/_vendor/distlib/t64.exe
     Lib/site-packages/pip/_vendor/distlib/w32.exe
     Lib/site-packages/pip/_vendor/distlib/w64-arm.exe
     Lib/site-packages/pip/_vendor/distlib/w64.exe
     Lib/site-packages/setuptools/cli-32.exe
     Lib/site-packages/setuptools/cli-64.exe
     Lib/site-packages/setuptools/cli-arm64.exe
     Lib/site-packages/setuptools/cli.exe
     Lib/site-packages/setuptools/gui-32.exe
     Lib/site-packages/setuptools/gui-64.exe
     Lib/site-packages/setuptools/gui-arm64.exe
     Lib/site-packages/setuptools/gui.exe
     Scripts/pip-3.11.exe
     Scripts/pip.exe
     Scripts/pip3.11.exe
     Scripts/pip3.exe
     Scripts/python.exe
     Scripts/pythonw.exe
     Scripts/wheel-3.11.exe
     Scripts/wheel.exe
     Scripts/wheel3.11.exe
     Scripts/wheel3.exe
   Source packages should not contain undeclared executable files.
   See section 'Package structure' in the 'Writing R Extensions' manual.
✔  checking for hidden files and directories ... 
W  checking for portable file names ... 
   Found the following files with non-portable file names:
     Lib/site-packages/setuptools/command/launcher manifest.xml
     Lib/site-packages/setuptools/script (dev).tmpl
   These are not fully portable file names.
   See section 'Package structure' in the 'Writing R Extensions' manual.
   Found the following non-portable file paths:
     teal.modules.clinical/Lib/site-packages/setuptools/config/_validate_pyproject/fastjsonschema_exceptions.py
     teal.modules.clinical/Lib/site-packages/setuptools/config/_validate_pyproject/fastjsonschema_validations.py
   
   Tarballs are only required to store paths of up to 100 bytes and cannot
   store those of more than 256 bytes, with restrictions including to 100
   bytes for the final component.
   See section 'Package structure' in the 'Writing R Extensions' manual.
✔  checking whether package 'teal.modules.clinical' can be installed (18.9s)
✔  checking installed package size (1.5s)
✔  checking package directory
✔  checking 'build' directory
✔  checking DESCRIPTION meta-information ... 
✔  checking top-level files
✔  checking for left-over files ... 
✔  checking index information ... 
✔  checking package subdirectories (1.8s)
✔  checking code files for non-ASCII characters ... 
✔  checking R files for syntax errors ... 
✔  checking whether the package can be loaded (1.7s)
✔  checking whether the package can be loaded with stated dependencies (2s)
✔  checking whether the package can be unloaded cleanly (1.9s)
✔  checking whether the namespace can be loaded with stated dependencies (2s)
✔  checking whether the namespace can be unloaded cleanly (2.3s)
✔  checking loading without being on the library search path (2.6s)
✔  checking whether startup messages can be suppressed (4.1s)
✔  checking dependencies in R code (3s)
✔  checking S3 generic/method consistency (1.8s)
✔  checking replacement functions (1.7s)
✔  checking foreign function calls (2.4s)
✔  checking R code for possible problems (14.6s)
✔  checking Rd files (1.8s)
✔  checking Rd metadata ... 
✔  checking Rd cross-references (443ms)
✔  checking for missing documentation entries (2.1s)
✔  checking for code/documentation mismatches (7.9s)
✔  checking Rd \usage sections (3.5s)
✔  checking Rd contents (555ms)
✔  checking for unstated dependencies in examples (1.7s)
✔  checking contents of 'data' directory ... 
✔  checking data for non-ASCII characters (344ms)
✔  checking LazyData
✔  checking data for ASCII and uncompressed saves ... 
✔  checking installed files from 'inst/doc' (657ms)
✔  checking files in 'vignettes' (368ms)
✔  checking examples (16.5s)
✔  checking for unstated dependencies in 'tests' ... 
─  checking tests (711ms)
✔  Running 'testthat.R' (30.5s)
✔  checking for unstated dependencies in vignettes (733ms)
✔  checking package vignettes (339ms)
✔  checking re-building of vignette outputs (14.7s)
✔  checking PDF version of manual (12.8s)
   
   See
     'C:/Users/kosinsm4/AppData/Local/Temp/Rtmp84khcL/file97c8d73e0e/teal.modules.clinical.Rcheck/00check.log'
   for details.
```

**Comment by m7pr** [comment]
`max_deps_check` failed

```r
ℹ Creating temporary DESCRIPTION file: C:\Users\kosinsm4\AppData\Local\Temp\Rtmp84khcL\file97c1df03357
ℹ Creating library directory: C:\Users\kosinsm4\AppData\Local\Temp\Rtmp84khcL\file97c71f7309c
Error : ! Could not solve package dependencies:                              
* deps::C:\Users\kosinsm4\AppData\Local\Temp\Rtmp84khcL\file97c1df03357:
  * Can't install dependency insightsengineering/tern
  * Can't install dependency insightsengineering/rlistings
  * Can't install dependency insightsengineering/rtables
* insightsengineering/tern: Can't install dependency formatters (>= 0.5.7.9000)
* insightsengineering/rlistings: Can't install dependency formatters (>= 0.5.7.9000)
* insightsengineering/rtables: Can't install dependency formatters (>= 0.5.7.9000)
```

**Review by m7pr — APPROVED** [review]
Ok it looks like it works for UNIX/Linux distros, but it fails for Windows in 2 scenarios. We do not support Windows yet, so we will merge this one one. The Windows issues might be different than the case fixed in here. We will focus on Windows builds once we get Windows in our CIs
